/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner{}

// OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner The object containing the list of fields required at a line level by the vendor.
type OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner struct {
	// The name of the line level field.
	AttributeName *string `json:"attributeName,omitempty"`
	// The value of the line level field.
	AttributeValue *string `json:"attributeValue,omitempty"`
}

// NewOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner instantiates a new OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner() *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner {
	this := OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner{}
	return &this
}

// NewOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInnerWithDefaults instantiates a new OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInnerWithDefaults() *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner {
	this := OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner{}
	return &this
}

// GetAttributeName returns the AttributeName field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) GetAttributeName() string {
	if o == nil || IsNil(o.AttributeName) {
		var ret string
		return ret
	}
	return *o.AttributeName
}

// GetAttributeNameOk returns a tuple with the AttributeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) GetAttributeNameOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeName) {
		return nil, false
	}
	return o.AttributeName, true
}

// HasAttributeName returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) HasAttributeName() bool {
	if o != nil && !IsNil(o.AttributeName) {
		return true
	}

	return false
}

// SetAttributeName gets a reference to the given string and assigns it to the AttributeName field.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) SetAttributeName(v string) {
	o.AttributeName = &v
}

// GetAttributeValue returns the AttributeValue field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) GetAttributeValue() string {
	if o == nil || IsNil(o.AttributeValue) {
		var ret string
		return ret
	}
	return *o.AttributeValue
}

// GetAttributeValueOk returns a tuple with the AttributeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) GetAttributeValueOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeValue) {
		return nil, false
	}
	return o.AttributeValue, true
}

// HasAttributeValue returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) HasAttributeValue() bool {
	if o != nil && !IsNil(o.AttributeValue) {
		return true
	}

	return false
}

// SetAttributeValue gets a reference to the given string and assigns it to the AttributeValue field.
func (o *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) SetAttributeValue(v string) {
	o.AttributeValue = &v
}

func (o OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeName) {
		toSerialize["attributeName"] = o.AttributeName
	}
	if !IsNil(o.AttributeValue) {
		toSerialize["attributeValue"] = o.AttributeValue
	}
	return toSerialize, nil
}

type NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner struct {
	value *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner
	isSet bool
}

func (v NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) Get() *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner {
	return v.value
}

func (v *NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) Set(val *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner(val *OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) *NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner {
	return &NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner{value: val, isSet: true}
}

func (v NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


