/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderCreateV7RequestLinesInnerBillingPeriod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateV7RequestLinesInnerBillingPeriod{}

// OrderCreateV7RequestLinesInnerBillingPeriod The object containing the list of options related to the billing period.
type OrderCreateV7RequestLinesInnerBillingPeriod struct {
	// Billing period of the subscription. Example, Years, Months
	Type *string `json:"type,omitempty"`
	// Length of the billing period. Example 1, 3
	Duration *int32 `json:"duration,omitempty"`
}

// NewOrderCreateV7RequestLinesInnerBillingPeriod instantiates a new OrderCreateV7RequestLinesInnerBillingPeriod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateV7RequestLinesInnerBillingPeriod() *OrderCreateV7RequestLinesInnerBillingPeriod {
	this := OrderCreateV7RequestLinesInnerBillingPeriod{}
	return &this
}

// NewOrderCreateV7RequestLinesInnerBillingPeriodWithDefaults instantiates a new OrderCreateV7RequestLinesInnerBillingPeriod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateV7RequestLinesInnerBillingPeriodWithDefaults() *OrderCreateV7RequestLinesInnerBillingPeriod {
	this := OrderCreateV7RequestLinesInnerBillingPeriod{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) SetType(v string) {
	o.Type = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *OrderCreateV7RequestLinesInnerBillingPeriod) SetDuration(v int32) {
	o.Duration = &v
}

func (o OrderCreateV7RequestLinesInnerBillingPeriod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateV7RequestLinesInnerBillingPeriod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

type NullableOrderCreateV7RequestLinesInnerBillingPeriod struct {
	value *OrderCreateV7RequestLinesInnerBillingPeriod
	isSet bool
}

func (v NullableOrderCreateV7RequestLinesInnerBillingPeriod) Get() *OrderCreateV7RequestLinesInnerBillingPeriod {
	return v.value
}

func (v *NullableOrderCreateV7RequestLinesInnerBillingPeriod) Set(val *OrderCreateV7RequestLinesInnerBillingPeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateV7RequestLinesInnerBillingPeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateV7RequestLinesInnerBillingPeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateV7RequestLinesInnerBillingPeriod(val *OrderCreateV7RequestLinesInnerBillingPeriod) *NullableOrderCreateV7RequestLinesInnerBillingPeriod {
	return &NullableOrderCreateV7RequestLinesInnerBillingPeriod{value: val, isSet: true}
}

func (v NullableOrderCreateV7RequestLinesInnerBillingPeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateV7RequestLinesInnerBillingPeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


