/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderCreateV7RequestLinesInnerAdditionalAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateV7RequestLinesInnerAdditionalAttributesInner{}

// OrderCreateV7RequestLinesInnerAdditionalAttributesInner struct for OrderCreateV7RequestLinesInnerAdditionalAttributesInner
type OrderCreateV7RequestLinesInnerAdditionalAttributesInner struct {
	// SAP requested and country-specific line level details.
	AttributeName *string `json:"attributeName,omitempty"`
	// TLine-level additional attributes.
	AttributeValue *string `json:"attributeValue,omitempty"`
}

// NewOrderCreateV7RequestLinesInnerAdditionalAttributesInner instantiates a new OrderCreateV7RequestLinesInnerAdditionalAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateV7RequestLinesInnerAdditionalAttributesInner() *OrderCreateV7RequestLinesInnerAdditionalAttributesInner {
	this := OrderCreateV7RequestLinesInnerAdditionalAttributesInner{}
	return &this
}

// NewOrderCreateV7RequestLinesInnerAdditionalAttributesInnerWithDefaults instantiates a new OrderCreateV7RequestLinesInnerAdditionalAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateV7RequestLinesInnerAdditionalAttributesInnerWithDefaults() *OrderCreateV7RequestLinesInnerAdditionalAttributesInner {
	this := OrderCreateV7RequestLinesInnerAdditionalAttributesInner{}
	return &this
}

// GetAttributeName returns the AttributeName field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) GetAttributeName() string {
	if o == nil || IsNil(o.AttributeName) {
		var ret string
		return ret
	}
	return *o.AttributeName
}

// GetAttributeNameOk returns a tuple with the AttributeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) GetAttributeNameOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeName) {
		return nil, false
	}
	return o.AttributeName, true
}

// HasAttributeName returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) HasAttributeName() bool {
	if o != nil && !IsNil(o.AttributeName) {
		return true
	}

	return false
}

// SetAttributeName gets a reference to the given string and assigns it to the AttributeName field.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) SetAttributeName(v string) {
	o.AttributeName = &v
}

// GetAttributeValue returns the AttributeValue field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) GetAttributeValue() string {
	if o == nil || IsNil(o.AttributeValue) {
		var ret string
		return ret
	}
	return *o.AttributeValue
}

// GetAttributeValueOk returns a tuple with the AttributeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) GetAttributeValueOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeValue) {
		return nil, false
	}
	return o.AttributeValue, true
}

// HasAttributeValue returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) HasAttributeValue() bool {
	if o != nil && !IsNil(o.AttributeValue) {
		return true
	}

	return false
}

// SetAttributeValue gets a reference to the given string and assigns it to the AttributeValue field.
func (o *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) SetAttributeValue(v string) {
	o.AttributeValue = &v
}

func (o OrderCreateV7RequestLinesInnerAdditionalAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateV7RequestLinesInnerAdditionalAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeName) {
		toSerialize["attributeName"] = o.AttributeName
	}
	if !IsNil(o.AttributeValue) {
		toSerialize["attributeValue"] = o.AttributeValue
	}
	return toSerialize, nil
}

type NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner struct {
	value *OrderCreateV7RequestLinesInnerAdditionalAttributesInner
	isSet bool
}

func (v NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner) Get() *OrderCreateV7RequestLinesInnerAdditionalAttributesInner {
	return v.value
}

func (v *NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner) Set(val *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner(val *OrderCreateV7RequestLinesInnerAdditionalAttributesInner) *NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner {
	return &NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner{value: val, isSet: true}
}

func (v NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateV7RequestLinesInnerAdditionalAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


