/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderDetailB2BLinesInnerEstimatedDatesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDetailB2BLinesInnerEstimatedDatesInner{}

// OrderDetailB2BLinesInnerEstimatedDatesInner struct for OrderDetailB2BLinesInnerEstimatedDatesInner
type OrderDetailB2BLinesInnerEstimatedDatesInner struct {
	Ship *OrderDetailB2BLinesInnerEstimatedDatesInnerShip `json:"ship,omitempty"`
	Delivery *OrderDetailB2BLinesInnerEstimatedDatesInnerDelivery `json:"delivery,omitempty"`
}

// NewOrderDetailB2BLinesInnerEstimatedDatesInner instantiates a new OrderDetailB2BLinesInnerEstimatedDatesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDetailB2BLinesInnerEstimatedDatesInner() *OrderDetailB2BLinesInnerEstimatedDatesInner {
	this := OrderDetailB2BLinesInnerEstimatedDatesInner{}
	return &this
}

// NewOrderDetailB2BLinesInnerEstimatedDatesInnerWithDefaults instantiates a new OrderDetailB2BLinesInnerEstimatedDatesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDetailB2BLinesInnerEstimatedDatesInnerWithDefaults() *OrderDetailB2BLinesInnerEstimatedDatesInner {
	this := OrderDetailB2BLinesInnerEstimatedDatesInner{}
	return &this
}

// GetShip returns the Ship field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) GetShip() OrderDetailB2BLinesInnerEstimatedDatesInnerShip {
	if o == nil || IsNil(o.Ship) {
		var ret OrderDetailB2BLinesInnerEstimatedDatesInnerShip
		return ret
	}
	return *o.Ship
}

// GetShipOk returns a tuple with the Ship field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) GetShipOk() (*OrderDetailB2BLinesInnerEstimatedDatesInnerShip, bool) {
	if o == nil || IsNil(o.Ship) {
		return nil, false
	}
	return o.Ship, true
}

// HasShip returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) HasShip() bool {
	if o != nil && !IsNil(o.Ship) {
		return true
	}

	return false
}

// SetShip gets a reference to the given OrderDetailB2BLinesInnerEstimatedDatesInnerShip and assigns it to the Ship field.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) SetShip(v OrderDetailB2BLinesInnerEstimatedDatesInnerShip) {
	o.Ship = &v
}

// GetDelivery returns the Delivery field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) GetDelivery() OrderDetailB2BLinesInnerEstimatedDatesInnerDelivery {
	if o == nil || IsNil(o.Delivery) {
		var ret OrderDetailB2BLinesInnerEstimatedDatesInnerDelivery
		return ret
	}
	return *o.Delivery
}

// GetDeliveryOk returns a tuple with the Delivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) GetDeliveryOk() (*OrderDetailB2BLinesInnerEstimatedDatesInnerDelivery, bool) {
	if o == nil || IsNil(o.Delivery) {
		return nil, false
	}
	return o.Delivery, true
}

// HasDelivery returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) HasDelivery() bool {
	if o != nil && !IsNil(o.Delivery) {
		return true
	}

	return false
}

// SetDelivery gets a reference to the given OrderDetailB2BLinesInnerEstimatedDatesInnerDelivery and assigns it to the Delivery field.
func (o *OrderDetailB2BLinesInnerEstimatedDatesInner) SetDelivery(v OrderDetailB2BLinesInnerEstimatedDatesInnerDelivery) {
	o.Delivery = &v
}

func (o OrderDetailB2BLinesInnerEstimatedDatesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDetailB2BLinesInnerEstimatedDatesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ship) {
		toSerialize["ship"] = o.Ship
	}
	if !IsNil(o.Delivery) {
		toSerialize["delivery"] = o.Delivery
	}
	return toSerialize, nil
}

type NullableOrderDetailB2BLinesInnerEstimatedDatesInner struct {
	value *OrderDetailB2BLinesInnerEstimatedDatesInner
	isSet bool
}

func (v NullableOrderDetailB2BLinesInnerEstimatedDatesInner) Get() *OrderDetailB2BLinesInnerEstimatedDatesInner {
	return v.value
}

func (v *NullableOrderDetailB2BLinesInnerEstimatedDatesInner) Set(val *OrderDetailB2BLinesInnerEstimatedDatesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDetailB2BLinesInnerEstimatedDatesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDetailB2BLinesInnerEstimatedDatesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDetailB2BLinesInnerEstimatedDatesInner(val *OrderDetailB2BLinesInnerEstimatedDatesInner) *NullableOrderDetailB2BLinesInnerEstimatedDatesInner {
	return &NullableOrderDetailB2BLinesInnerEstimatedDatesInner{value: val, isSet: true}
}

func (v NullableOrderDetailB2BLinesInnerEstimatedDatesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDetailB2BLinesInnerEstimatedDatesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


