/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderCreateV7RequestLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateV7RequestLinesInner{}

// OrderCreateV7RequestLinesInner struct for OrderCreateV7RequestLinesInner
type OrderCreateV7RequestLinesInner struct {
	// The reseller's line item number for reference in their system. The customer line number needs to be a unique numeric value between 1 and 884. In the event we receive duplicate values or alphanumeric values in the customer line number, we will re-sequence the customer line number. To prevent re-sequencing, please use a unique numeric value between 1 and 884 in the customer line number.
	CustomerLineNumber *string `json:"customerLineNumber,omitempty"`
	// The unique IngramMicro part number.
	IngramPartNumber *string `json:"ingramPartNumber,omitempty"`
	// The vendor's part number for the line item.
	VendorPartNumber *string `json:"vendorPartNumber,omitempty"`
	// The requested quantity of the line item.
	Quantity *int32 `json:"quantity,omitempty"`
	// The reseller-requested unit price for the line item. The unit price is not guaranteed.
	UnitPrice *float32 `json:"unitPrice,omitempty"`
	// The line-level bid number provided to the reseller by the vendor for special pricing and discounts. Used to track the bid number in the case of split orders or where different line items have different bid numbers. Line-level bid number take precedence over header-level bid numbers.
	SpecialBidNumber *string `json:"specialBidNumber,omitempty"`
	// The end-user price. Required for Export Orders.
	EndUserPrice *float32 `json:"endUserPrice,omitempty"`
	// The attribute field data.
	Notes *string `json:"notes,omitempty"`
	// The resource id of the subscription
	ResourceId *string `json:"resourceId,omitempty"`
	// ID of the subscription plan
	Planid *string `json:"planid,omitempty"`
	SubscriptionPeriod *OrderCreateV7RequestLinesInnerSubscriptionPeriod `json:"subscriptionPeriod,omitempty"`
	BillingPeriod *OrderCreateV7RequestLinesInnerBillingPeriod `json:"billingPeriod,omitempty"`
	// Line-level margin requested by customer
	Margin *float32 `json:"margin,omitempty"`
	// Line-level end-customer price requsted by customer
	EndCustomerPrice *float32 `json:"endCustomerPrice,omitempty"`
	// The object containing the list of Vendor Mandatory Fields required by the vendor for the subscription products.
	VriAdditionalAttributes []OrderCreateV7RequestVmfVendorAdditionalAttributesInner `json:"vriAdditionalAttributes,omitempty"`
	EndUserInfo []OrderCreateV7RequestLinesInnerEndUserInfoInner `json:"endUserInfo,omitempty"`
	AdditionalAttributes []OrderCreateV7RequestLinesInnerAdditionalAttributesInner `json:"additionalAttributes,omitempty"`
	WarrantyInfo *OrderCreateV7RequestLinesInnerWarrantyInfo `json:"warrantyInfo,omitempty"`
	// The object containing the list of fields required at a line level by the vendor.<br> This a <code>Deprecated</code> object. Kindly use <b>vmfVendorAdditionalAttributes</b> object
	VmfAdditionalAttributesLines []OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner `json:"vmfAdditionalAttributesLines,omitempty"`
}

// NewOrderCreateV7RequestLinesInner instantiates a new OrderCreateV7RequestLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateV7RequestLinesInner() *OrderCreateV7RequestLinesInner {
	this := OrderCreateV7RequestLinesInner{}
	return &this
}

// NewOrderCreateV7RequestLinesInnerWithDefaults instantiates a new OrderCreateV7RequestLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateV7RequestLinesInnerWithDefaults() *OrderCreateV7RequestLinesInner {
	this := OrderCreateV7RequestLinesInner{}
	return &this
}

// GetCustomerLineNumber returns the CustomerLineNumber field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetCustomerLineNumber() string {
	if o == nil || IsNil(o.CustomerLineNumber) {
		var ret string
		return ret
	}
	return *o.CustomerLineNumber
}

// GetCustomerLineNumberOk returns a tuple with the CustomerLineNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetCustomerLineNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerLineNumber) {
		return nil, false
	}
	return o.CustomerLineNumber, true
}

// HasCustomerLineNumber returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasCustomerLineNumber() bool {
	if o != nil && !IsNil(o.CustomerLineNumber) {
		return true
	}

	return false
}

// SetCustomerLineNumber gets a reference to the given string and assigns it to the CustomerLineNumber field.
func (o *OrderCreateV7RequestLinesInner) SetCustomerLineNumber(v string) {
	o.CustomerLineNumber = &v
}

// GetIngramPartNumber returns the IngramPartNumber field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetIngramPartNumber() string {
	if o == nil || IsNil(o.IngramPartNumber) {
		var ret string
		return ret
	}
	return *o.IngramPartNumber
}

// GetIngramPartNumberOk returns a tuple with the IngramPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetIngramPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.IngramPartNumber) {
		return nil, false
	}
	return o.IngramPartNumber, true
}

// HasIngramPartNumber returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasIngramPartNumber() bool {
	if o != nil && !IsNil(o.IngramPartNumber) {
		return true
	}

	return false
}

// SetIngramPartNumber gets a reference to the given string and assigns it to the IngramPartNumber field.
func (o *OrderCreateV7RequestLinesInner) SetIngramPartNumber(v string) {
	o.IngramPartNumber = &v
}

// GetVendorPartNumber returns the VendorPartNumber field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetVendorPartNumber() string {
	if o == nil || IsNil(o.VendorPartNumber) {
		var ret string
		return ret
	}
	return *o.VendorPartNumber
}

// GetVendorPartNumberOk returns a tuple with the VendorPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetVendorPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.VendorPartNumber) {
		return nil, false
	}
	return o.VendorPartNumber, true
}

// HasVendorPartNumber returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasVendorPartNumber() bool {
	if o != nil && !IsNil(o.VendorPartNumber) {
		return true
	}

	return false
}

// SetVendorPartNumber gets a reference to the given string and assigns it to the VendorPartNumber field.
func (o *OrderCreateV7RequestLinesInner) SetVendorPartNumber(v string) {
	o.VendorPartNumber = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *OrderCreateV7RequestLinesInner) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetUnitPrice() float32 {
	if o == nil || IsNil(o.UnitPrice) {
		var ret float32
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetUnitPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given float32 and assigns it to the UnitPrice field.
func (o *OrderCreateV7RequestLinesInner) SetUnitPrice(v float32) {
	o.UnitPrice = &v
}

// GetSpecialBidNumber returns the SpecialBidNumber field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetSpecialBidNumber() string {
	if o == nil || IsNil(o.SpecialBidNumber) {
		var ret string
		return ret
	}
	return *o.SpecialBidNumber
}

// GetSpecialBidNumberOk returns a tuple with the SpecialBidNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetSpecialBidNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SpecialBidNumber) {
		return nil, false
	}
	return o.SpecialBidNumber, true
}

// HasSpecialBidNumber returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasSpecialBidNumber() bool {
	if o != nil && !IsNil(o.SpecialBidNumber) {
		return true
	}

	return false
}

// SetSpecialBidNumber gets a reference to the given string and assigns it to the SpecialBidNumber field.
func (o *OrderCreateV7RequestLinesInner) SetSpecialBidNumber(v string) {
	o.SpecialBidNumber = &v
}

// GetEndUserPrice returns the EndUserPrice field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetEndUserPrice() float32 {
	if o == nil || IsNil(o.EndUserPrice) {
		var ret float32
		return ret
	}
	return *o.EndUserPrice
}

// GetEndUserPriceOk returns a tuple with the EndUserPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetEndUserPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.EndUserPrice) {
		return nil, false
	}
	return o.EndUserPrice, true
}

// HasEndUserPrice returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasEndUserPrice() bool {
	if o != nil && !IsNil(o.EndUserPrice) {
		return true
	}

	return false
}

// SetEndUserPrice gets a reference to the given float32 and assigns it to the EndUserPrice field.
func (o *OrderCreateV7RequestLinesInner) SetEndUserPrice(v float32) {
	o.EndUserPrice = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *OrderCreateV7RequestLinesInner) SetNotes(v string) {
	o.Notes = &v
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId) {
		var ret string
		return ret
	}
	return *o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetResourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceId) {
		return nil, false
	}
	return o.ResourceId, true
}

// HasResourceId returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasResourceId() bool {
	if o != nil && !IsNil(o.ResourceId) {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given string and assigns it to the ResourceId field.
func (o *OrderCreateV7RequestLinesInner) SetResourceId(v string) {
	o.ResourceId = &v
}

// GetPlanid returns the Planid field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetPlanid() string {
	if o == nil || IsNil(o.Planid) {
		var ret string
		return ret
	}
	return *o.Planid
}

// GetPlanidOk returns a tuple with the Planid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetPlanidOk() (*string, bool) {
	if o == nil || IsNil(o.Planid) {
		return nil, false
	}
	return o.Planid, true
}

// HasPlanid returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasPlanid() bool {
	if o != nil && !IsNil(o.Planid) {
		return true
	}

	return false
}

// SetPlanid gets a reference to the given string and assigns it to the Planid field.
func (o *OrderCreateV7RequestLinesInner) SetPlanid(v string) {
	o.Planid = &v
}

// GetSubscriptionPeriod returns the SubscriptionPeriod field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetSubscriptionPeriod() OrderCreateV7RequestLinesInnerSubscriptionPeriod {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		var ret OrderCreateV7RequestLinesInnerSubscriptionPeriod
		return ret
	}
	return *o.SubscriptionPeriod
}

// GetSubscriptionPeriodOk returns a tuple with the SubscriptionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetSubscriptionPeriodOk() (*OrderCreateV7RequestLinesInnerSubscriptionPeriod, bool) {
	if o == nil || IsNil(o.SubscriptionPeriod) {
		return nil, false
	}
	return o.SubscriptionPeriod, true
}

// HasSubscriptionPeriod returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasSubscriptionPeriod() bool {
	if o != nil && !IsNil(o.SubscriptionPeriod) {
		return true
	}

	return false
}

// SetSubscriptionPeriod gets a reference to the given OrderCreateV7RequestLinesInnerSubscriptionPeriod and assigns it to the SubscriptionPeriod field.
func (o *OrderCreateV7RequestLinesInner) SetSubscriptionPeriod(v OrderCreateV7RequestLinesInnerSubscriptionPeriod) {
	o.SubscriptionPeriod = &v
}

// GetBillingPeriod returns the BillingPeriod field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetBillingPeriod() OrderCreateV7RequestLinesInnerBillingPeriod {
	if o == nil || IsNil(o.BillingPeriod) {
		var ret OrderCreateV7RequestLinesInnerBillingPeriod
		return ret
	}
	return *o.BillingPeriod
}

// GetBillingPeriodOk returns a tuple with the BillingPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetBillingPeriodOk() (*OrderCreateV7RequestLinesInnerBillingPeriod, bool) {
	if o == nil || IsNil(o.BillingPeriod) {
		return nil, false
	}
	return o.BillingPeriod, true
}

// HasBillingPeriod returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasBillingPeriod() bool {
	if o != nil && !IsNil(o.BillingPeriod) {
		return true
	}

	return false
}

// SetBillingPeriod gets a reference to the given OrderCreateV7RequestLinesInnerBillingPeriod and assigns it to the BillingPeriod field.
func (o *OrderCreateV7RequestLinesInner) SetBillingPeriod(v OrderCreateV7RequestLinesInnerBillingPeriod) {
	o.BillingPeriod = &v
}

// GetMargin returns the Margin field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetMargin() float32 {
	if o == nil || IsNil(o.Margin) {
		var ret float32
		return ret
	}
	return *o.Margin
}

// GetMarginOk returns a tuple with the Margin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetMarginOk() (*float32, bool) {
	if o == nil || IsNil(o.Margin) {
		return nil, false
	}
	return o.Margin, true
}

// HasMargin returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasMargin() bool {
	if o != nil && !IsNil(o.Margin) {
		return true
	}

	return false
}

// SetMargin gets a reference to the given float32 and assigns it to the Margin field.
func (o *OrderCreateV7RequestLinesInner) SetMargin(v float32) {
	o.Margin = &v
}

// GetEndCustomerPrice returns the EndCustomerPrice field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetEndCustomerPrice() float32 {
	if o == nil || IsNil(o.EndCustomerPrice) {
		var ret float32
		return ret
	}
	return *o.EndCustomerPrice
}

// GetEndCustomerPriceOk returns a tuple with the EndCustomerPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetEndCustomerPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.EndCustomerPrice) {
		return nil, false
	}
	return o.EndCustomerPrice, true
}

// HasEndCustomerPrice returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasEndCustomerPrice() bool {
	if o != nil && !IsNil(o.EndCustomerPrice) {
		return true
	}

	return false
}

// SetEndCustomerPrice gets a reference to the given float32 and assigns it to the EndCustomerPrice field.
func (o *OrderCreateV7RequestLinesInner) SetEndCustomerPrice(v float32) {
	o.EndCustomerPrice = &v
}

// GetVriAdditionalAttributes returns the VriAdditionalAttributes field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetVriAdditionalAttributes() []OrderCreateV7RequestVmfVendorAdditionalAttributesInner {
	if o == nil || IsNil(o.VriAdditionalAttributes) {
		var ret []OrderCreateV7RequestVmfVendorAdditionalAttributesInner
		return ret
	}
	return o.VriAdditionalAttributes
}

// GetVriAdditionalAttributesOk returns a tuple with the VriAdditionalAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetVriAdditionalAttributesOk() ([]OrderCreateV7RequestVmfVendorAdditionalAttributesInner, bool) {
	if o == nil || IsNil(o.VriAdditionalAttributes) {
		return nil, false
	}
	return o.VriAdditionalAttributes, true
}

// HasVriAdditionalAttributes returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasVriAdditionalAttributes() bool {
	if o != nil && !IsNil(o.VriAdditionalAttributes) {
		return true
	}

	return false
}

// SetVriAdditionalAttributes gets a reference to the given []OrderCreateV7RequestVmfVendorAdditionalAttributesInner and assigns it to the VriAdditionalAttributes field.
func (o *OrderCreateV7RequestLinesInner) SetVriAdditionalAttributes(v []OrderCreateV7RequestVmfVendorAdditionalAttributesInner) {
	o.VriAdditionalAttributes = v
}

// GetEndUserInfo returns the EndUserInfo field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetEndUserInfo() []OrderCreateV7RequestLinesInnerEndUserInfoInner {
	if o == nil || IsNil(o.EndUserInfo) {
		var ret []OrderCreateV7RequestLinesInnerEndUserInfoInner
		return ret
	}
	return o.EndUserInfo
}

// GetEndUserInfoOk returns a tuple with the EndUserInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetEndUserInfoOk() ([]OrderCreateV7RequestLinesInnerEndUserInfoInner, bool) {
	if o == nil || IsNil(o.EndUserInfo) {
		return nil, false
	}
	return o.EndUserInfo, true
}

// HasEndUserInfo returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasEndUserInfo() bool {
	if o != nil && !IsNil(o.EndUserInfo) {
		return true
	}

	return false
}

// SetEndUserInfo gets a reference to the given []OrderCreateV7RequestLinesInnerEndUserInfoInner and assigns it to the EndUserInfo field.
func (o *OrderCreateV7RequestLinesInner) SetEndUserInfo(v []OrderCreateV7RequestLinesInnerEndUserInfoInner) {
	o.EndUserInfo = v
}

// GetAdditionalAttributes returns the AdditionalAttributes field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetAdditionalAttributes() []OrderCreateV7RequestLinesInnerAdditionalAttributesInner {
	if o == nil || IsNil(o.AdditionalAttributes) {
		var ret []OrderCreateV7RequestLinesInnerAdditionalAttributesInner
		return ret
	}
	return o.AdditionalAttributes
}

// GetAdditionalAttributesOk returns a tuple with the AdditionalAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetAdditionalAttributesOk() ([]OrderCreateV7RequestLinesInnerAdditionalAttributesInner, bool) {
	if o == nil || IsNil(o.AdditionalAttributes) {
		return nil, false
	}
	return o.AdditionalAttributes, true
}

// HasAdditionalAttributes returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasAdditionalAttributes() bool {
	if o != nil && !IsNil(o.AdditionalAttributes) {
		return true
	}

	return false
}

// SetAdditionalAttributes gets a reference to the given []OrderCreateV7RequestLinesInnerAdditionalAttributesInner and assigns it to the AdditionalAttributes field.
func (o *OrderCreateV7RequestLinesInner) SetAdditionalAttributes(v []OrderCreateV7RequestLinesInnerAdditionalAttributesInner) {
	o.AdditionalAttributes = v
}

// GetWarrantyInfo returns the WarrantyInfo field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetWarrantyInfo() OrderCreateV7RequestLinesInnerWarrantyInfo {
	if o == nil || IsNil(o.WarrantyInfo) {
		var ret OrderCreateV7RequestLinesInnerWarrantyInfo
		return ret
	}
	return *o.WarrantyInfo
}

// GetWarrantyInfoOk returns a tuple with the WarrantyInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetWarrantyInfoOk() (*OrderCreateV7RequestLinesInnerWarrantyInfo, bool) {
	if o == nil || IsNil(o.WarrantyInfo) {
		return nil, false
	}
	return o.WarrantyInfo, true
}

// HasWarrantyInfo returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasWarrantyInfo() bool {
	if o != nil && !IsNil(o.WarrantyInfo) {
		return true
	}

	return false
}

// SetWarrantyInfo gets a reference to the given OrderCreateV7RequestLinesInnerWarrantyInfo and assigns it to the WarrantyInfo field.
func (o *OrderCreateV7RequestLinesInner) SetWarrantyInfo(v OrderCreateV7RequestLinesInnerWarrantyInfo) {
	o.WarrantyInfo = &v
}

// GetVmfAdditionalAttributesLines returns the VmfAdditionalAttributesLines field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInner) GetVmfAdditionalAttributesLines() []OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner {
	if o == nil || IsNil(o.VmfAdditionalAttributesLines) {
		var ret []OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner
		return ret
	}
	return o.VmfAdditionalAttributesLines
}

// GetVmfAdditionalAttributesLinesOk returns a tuple with the VmfAdditionalAttributesLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInner) GetVmfAdditionalAttributesLinesOk() ([]OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner, bool) {
	if o == nil || IsNil(o.VmfAdditionalAttributesLines) {
		return nil, false
	}
	return o.VmfAdditionalAttributesLines, true
}

// HasVmfAdditionalAttributesLines returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInner) HasVmfAdditionalAttributesLines() bool {
	if o != nil && !IsNil(o.VmfAdditionalAttributesLines) {
		return true
	}

	return false
}

// SetVmfAdditionalAttributesLines gets a reference to the given []OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner and assigns it to the VmfAdditionalAttributesLines field.
func (o *OrderCreateV7RequestLinesInner) SetVmfAdditionalAttributesLines(v []OrderCreateV7RequestLinesInnerVmfAdditionalAttributesLinesInner) {
	o.VmfAdditionalAttributesLines = v
}

func (o OrderCreateV7RequestLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateV7RequestLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerLineNumber) {
		toSerialize["customerLineNumber"] = o.CustomerLineNumber
	}
	if !IsNil(o.IngramPartNumber) {
		toSerialize["ingramPartNumber"] = o.IngramPartNumber
	}
	if !IsNil(o.VendorPartNumber) {
		toSerialize["vendorPartNumber"] = o.VendorPartNumber
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if !IsNil(o.SpecialBidNumber) {
		toSerialize["specialBidNumber"] = o.SpecialBidNumber
	}
	if !IsNil(o.EndUserPrice) {
		toSerialize["endUserPrice"] = o.EndUserPrice
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.ResourceId) {
		toSerialize["resourceId"] = o.ResourceId
	}
	if !IsNil(o.Planid) {
		toSerialize["planid"] = o.Planid
	}
	if !IsNil(o.SubscriptionPeriod) {
		toSerialize["subscriptionPeriod"] = o.SubscriptionPeriod
	}
	if !IsNil(o.BillingPeriod) {
		toSerialize["billingPeriod"] = o.BillingPeriod
	}
	if !IsNil(o.Margin) {
		toSerialize["margin"] = o.Margin
	}
	if !IsNil(o.EndCustomerPrice) {
		toSerialize["endCustomerPrice"] = o.EndCustomerPrice
	}
	if !IsNil(o.VriAdditionalAttributes) {
		toSerialize["vriAdditionalAttributes"] = o.VriAdditionalAttributes
	}
	if !IsNil(o.EndUserInfo) {
		toSerialize["endUserInfo"] = o.EndUserInfo
	}
	if !IsNil(o.AdditionalAttributes) {
		toSerialize["additionalAttributes"] = o.AdditionalAttributes
	}
	if !IsNil(o.WarrantyInfo) {
		toSerialize["warrantyInfo"] = o.WarrantyInfo
	}
	if !IsNil(o.VmfAdditionalAttributesLines) {
		toSerialize["vmfAdditionalAttributesLines"] = o.VmfAdditionalAttributesLines
	}
	return toSerialize, nil
}

type NullableOrderCreateV7RequestLinesInner struct {
	value *OrderCreateV7RequestLinesInner
	isSet bool
}

func (v NullableOrderCreateV7RequestLinesInner) Get() *OrderCreateV7RequestLinesInner {
	return v.value
}

func (v *NullableOrderCreateV7RequestLinesInner) Set(val *OrderCreateV7RequestLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateV7RequestLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateV7RequestLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateV7RequestLinesInner(val *OrderCreateV7RequestLinesInner) *NullableOrderCreateV7RequestLinesInner {
	return &NullableOrderCreateV7RequestLinesInner{value: val, isSet: true}
}

func (v NullableOrderCreateV7RequestLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateV7RequestLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


