/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderCreateResponseOrdersInnerLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateResponseOrdersInnerLinesInner{}

// OrderCreateResponseOrdersInnerLinesInner struct for OrderCreateResponseOrdersInnerLinesInner
type OrderCreateResponseOrdersInnerLinesInner struct {
	// The sub order number. The two-digit prefix is the warehouse code of the warehouse nearest the reseller. The middle number is the order number. The two-digit suffix is the sub order number.
	SubOrderNumber *string `json:"subOrderNumber,omitempty"`
	// The Ingram Micro line number for the product.
	IngramLineNumber *string `json:"ingramLineNumber,omitempty"`
	// The reseller's line number for reference in their system.
	CustomerLineNumber *string `json:"customerLineNumber,omitempty"`
	// The status for the line item in the order. One of: Backordered, Open
	LineStatus *string `json:"lineStatus,omitempty"`
	// The Ingram Micro part number for the line item.
	IngramPartNumber *string `json:"ingramPartNumber,omitempty"`
	// The vendor part number for the line item.
	VendorPartNumber *string `json:"vendorPartNumber,omitempty"`
	// The unit price for the line item.
	UnitPrice *float32 `json:"unitPrice,omitempty"`
	// The extended list price (unit price X quantity) for the line item.
	ExtendedUnitPrice *float32 `json:"extendedUnitPrice,omitempty"`
	// The quantity of the line item ordered.
	QuantityOrdered *int32 `json:"quantityOrdered,omitempty"`
	// The quantity of the line item that has been confirmed.
	QuantityConfirmed *int32 `json:"quantityConfirmed,omitempty"`
	// The quantity of the line item that is backordered.
	QuantityBackOrdered *int32 `json:"quantityBackOrdered,omitempty"`
	// The bid number for the line item provided to the reseller by the vendor for special pricing and discounts. Line-level bid numbers take precedence over header-level bid numbers.
	SpecialBidNumber *string `json:"specialBidNumber,omitempty"`
	// Line-level notes.
	Notes *string `json:"notes,omitempty"`
	// The shipment details for the line item.
	ShipmentDetails []OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner `json:"shipmentDetails,omitempty"`
	// SAP requested and country-specific line level details.
	AdditionalAttributes []OrderCreateResponseOrdersInnerLinesInnerAdditionalAttributesInner `json:"additionalAttributes,omitempty"`
}

// NewOrderCreateResponseOrdersInnerLinesInner instantiates a new OrderCreateResponseOrdersInnerLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateResponseOrdersInnerLinesInner() *OrderCreateResponseOrdersInnerLinesInner {
	this := OrderCreateResponseOrdersInnerLinesInner{}
	return &this
}

// NewOrderCreateResponseOrdersInnerLinesInnerWithDefaults instantiates a new OrderCreateResponseOrdersInnerLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateResponseOrdersInnerLinesInnerWithDefaults() *OrderCreateResponseOrdersInnerLinesInner {
	this := OrderCreateResponseOrdersInnerLinesInner{}
	return &this
}

// GetSubOrderNumber returns the SubOrderNumber field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetSubOrderNumber() string {
	if o == nil || IsNil(o.SubOrderNumber) {
		var ret string
		return ret
	}
	return *o.SubOrderNumber
}

// GetSubOrderNumberOk returns a tuple with the SubOrderNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetSubOrderNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SubOrderNumber) {
		return nil, false
	}
	return o.SubOrderNumber, true
}

// HasSubOrderNumber returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasSubOrderNumber() bool {
	if o != nil && !IsNil(o.SubOrderNumber) {
		return true
	}

	return false
}

// SetSubOrderNumber gets a reference to the given string and assigns it to the SubOrderNumber field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetSubOrderNumber(v string) {
	o.SubOrderNumber = &v
}

// GetIngramLineNumber returns the IngramLineNumber field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetIngramLineNumber() string {
	if o == nil || IsNil(o.IngramLineNumber) {
		var ret string
		return ret
	}
	return *o.IngramLineNumber
}

// GetIngramLineNumberOk returns a tuple with the IngramLineNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetIngramLineNumberOk() (*string, bool) {
	if o == nil || IsNil(o.IngramLineNumber) {
		return nil, false
	}
	return o.IngramLineNumber, true
}

// HasIngramLineNumber returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasIngramLineNumber() bool {
	if o != nil && !IsNil(o.IngramLineNumber) {
		return true
	}

	return false
}

// SetIngramLineNumber gets a reference to the given string and assigns it to the IngramLineNumber field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetIngramLineNumber(v string) {
	o.IngramLineNumber = &v
}

// GetCustomerLineNumber returns the CustomerLineNumber field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetCustomerLineNumber() string {
	if o == nil || IsNil(o.CustomerLineNumber) {
		var ret string
		return ret
	}
	return *o.CustomerLineNumber
}

// GetCustomerLineNumberOk returns a tuple with the CustomerLineNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetCustomerLineNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerLineNumber) {
		return nil, false
	}
	return o.CustomerLineNumber, true
}

// HasCustomerLineNumber returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasCustomerLineNumber() bool {
	if o != nil && !IsNil(o.CustomerLineNumber) {
		return true
	}

	return false
}

// SetCustomerLineNumber gets a reference to the given string and assigns it to the CustomerLineNumber field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetCustomerLineNumber(v string) {
	o.CustomerLineNumber = &v
}

// GetLineStatus returns the LineStatus field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetLineStatus() string {
	if o == nil || IsNil(o.LineStatus) {
		var ret string
		return ret
	}
	return *o.LineStatus
}

// GetLineStatusOk returns a tuple with the LineStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetLineStatusOk() (*string, bool) {
	if o == nil || IsNil(o.LineStatus) {
		return nil, false
	}
	return o.LineStatus, true
}

// HasLineStatus returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasLineStatus() bool {
	if o != nil && !IsNil(o.LineStatus) {
		return true
	}

	return false
}

// SetLineStatus gets a reference to the given string and assigns it to the LineStatus field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetLineStatus(v string) {
	o.LineStatus = &v
}

// GetIngramPartNumber returns the IngramPartNumber field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetIngramPartNumber() string {
	if o == nil || IsNil(o.IngramPartNumber) {
		var ret string
		return ret
	}
	return *o.IngramPartNumber
}

// GetIngramPartNumberOk returns a tuple with the IngramPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetIngramPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.IngramPartNumber) {
		return nil, false
	}
	return o.IngramPartNumber, true
}

// HasIngramPartNumber returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasIngramPartNumber() bool {
	if o != nil && !IsNil(o.IngramPartNumber) {
		return true
	}

	return false
}

// SetIngramPartNumber gets a reference to the given string and assigns it to the IngramPartNumber field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetIngramPartNumber(v string) {
	o.IngramPartNumber = &v
}

// GetVendorPartNumber returns the VendorPartNumber field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetVendorPartNumber() string {
	if o == nil || IsNil(o.VendorPartNumber) {
		var ret string
		return ret
	}
	return *o.VendorPartNumber
}

// GetVendorPartNumberOk returns a tuple with the VendorPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetVendorPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.VendorPartNumber) {
		return nil, false
	}
	return o.VendorPartNumber, true
}

// HasVendorPartNumber returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasVendorPartNumber() bool {
	if o != nil && !IsNil(o.VendorPartNumber) {
		return true
	}

	return false
}

// SetVendorPartNumber gets a reference to the given string and assigns it to the VendorPartNumber field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetVendorPartNumber(v string) {
	o.VendorPartNumber = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetUnitPrice() float32 {
	if o == nil || IsNil(o.UnitPrice) {
		var ret float32
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetUnitPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given float32 and assigns it to the UnitPrice field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetUnitPrice(v float32) {
	o.UnitPrice = &v
}

// GetExtendedUnitPrice returns the ExtendedUnitPrice field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetExtendedUnitPrice() float32 {
	if o == nil || IsNil(o.ExtendedUnitPrice) {
		var ret float32
		return ret
	}
	return *o.ExtendedUnitPrice
}

// GetExtendedUnitPriceOk returns a tuple with the ExtendedUnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetExtendedUnitPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.ExtendedUnitPrice) {
		return nil, false
	}
	return o.ExtendedUnitPrice, true
}

// HasExtendedUnitPrice returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasExtendedUnitPrice() bool {
	if o != nil && !IsNil(o.ExtendedUnitPrice) {
		return true
	}

	return false
}

// SetExtendedUnitPrice gets a reference to the given float32 and assigns it to the ExtendedUnitPrice field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetExtendedUnitPrice(v float32) {
	o.ExtendedUnitPrice = &v
}

// GetQuantityOrdered returns the QuantityOrdered field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetQuantityOrdered() int32 {
	if o == nil || IsNil(o.QuantityOrdered) {
		var ret int32
		return ret
	}
	return *o.QuantityOrdered
}

// GetQuantityOrderedOk returns a tuple with the QuantityOrdered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetQuantityOrderedOk() (*int32, bool) {
	if o == nil || IsNil(o.QuantityOrdered) {
		return nil, false
	}
	return o.QuantityOrdered, true
}

// HasQuantityOrdered returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasQuantityOrdered() bool {
	if o != nil && !IsNil(o.QuantityOrdered) {
		return true
	}

	return false
}

// SetQuantityOrdered gets a reference to the given int32 and assigns it to the QuantityOrdered field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetQuantityOrdered(v int32) {
	o.QuantityOrdered = &v
}

// GetQuantityConfirmed returns the QuantityConfirmed field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetQuantityConfirmed() int32 {
	if o == nil || IsNil(o.QuantityConfirmed) {
		var ret int32
		return ret
	}
	return *o.QuantityConfirmed
}

// GetQuantityConfirmedOk returns a tuple with the QuantityConfirmed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetQuantityConfirmedOk() (*int32, bool) {
	if o == nil || IsNil(o.QuantityConfirmed) {
		return nil, false
	}
	return o.QuantityConfirmed, true
}

// HasQuantityConfirmed returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasQuantityConfirmed() bool {
	if o != nil && !IsNil(o.QuantityConfirmed) {
		return true
	}

	return false
}

// SetQuantityConfirmed gets a reference to the given int32 and assigns it to the QuantityConfirmed field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetQuantityConfirmed(v int32) {
	o.QuantityConfirmed = &v
}

// GetQuantityBackOrdered returns the QuantityBackOrdered field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetQuantityBackOrdered() int32 {
	if o == nil || IsNil(o.QuantityBackOrdered) {
		var ret int32
		return ret
	}
	return *o.QuantityBackOrdered
}

// GetQuantityBackOrderedOk returns a tuple with the QuantityBackOrdered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetQuantityBackOrderedOk() (*int32, bool) {
	if o == nil || IsNil(o.QuantityBackOrdered) {
		return nil, false
	}
	return o.QuantityBackOrdered, true
}

// HasQuantityBackOrdered returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasQuantityBackOrdered() bool {
	if o != nil && !IsNil(o.QuantityBackOrdered) {
		return true
	}

	return false
}

// SetQuantityBackOrdered gets a reference to the given int32 and assigns it to the QuantityBackOrdered field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetQuantityBackOrdered(v int32) {
	o.QuantityBackOrdered = &v
}

// GetSpecialBidNumber returns the SpecialBidNumber field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetSpecialBidNumber() string {
	if o == nil || IsNil(o.SpecialBidNumber) {
		var ret string
		return ret
	}
	return *o.SpecialBidNumber
}

// GetSpecialBidNumberOk returns a tuple with the SpecialBidNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetSpecialBidNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SpecialBidNumber) {
		return nil, false
	}
	return o.SpecialBidNumber, true
}

// HasSpecialBidNumber returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasSpecialBidNumber() bool {
	if o != nil && !IsNil(o.SpecialBidNumber) {
		return true
	}

	return false
}

// SetSpecialBidNumber gets a reference to the given string and assigns it to the SpecialBidNumber field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetSpecialBidNumber(v string) {
	o.SpecialBidNumber = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetNotes(v string) {
	o.Notes = &v
}

// GetShipmentDetails returns the ShipmentDetails field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetShipmentDetails() []OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner {
	if o == nil || IsNil(o.ShipmentDetails) {
		var ret []OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner
		return ret
	}
	return o.ShipmentDetails
}

// GetShipmentDetailsOk returns a tuple with the ShipmentDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetShipmentDetailsOk() ([]OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner, bool) {
	if o == nil || IsNil(o.ShipmentDetails) {
		return nil, false
	}
	return o.ShipmentDetails, true
}

// HasShipmentDetails returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasShipmentDetails() bool {
	if o != nil && !IsNil(o.ShipmentDetails) {
		return true
	}

	return false
}

// SetShipmentDetails gets a reference to the given []OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner and assigns it to the ShipmentDetails field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetShipmentDetails(v []OrderCreateResponseOrdersInnerLinesInnerShipmentDetailsInner) {
	o.ShipmentDetails = v
}

// GetAdditionalAttributes returns the AdditionalAttributes field value if set, zero value otherwise.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetAdditionalAttributes() []OrderCreateResponseOrdersInnerLinesInnerAdditionalAttributesInner {
	if o == nil || IsNil(o.AdditionalAttributes) {
		var ret []OrderCreateResponseOrdersInnerLinesInnerAdditionalAttributesInner
		return ret
	}
	return o.AdditionalAttributes
}

// GetAdditionalAttributesOk returns a tuple with the AdditionalAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) GetAdditionalAttributesOk() ([]OrderCreateResponseOrdersInnerLinesInnerAdditionalAttributesInner, bool) {
	if o == nil || IsNil(o.AdditionalAttributes) {
		return nil, false
	}
	return o.AdditionalAttributes, true
}

// HasAdditionalAttributes returns a boolean if a field has been set.
func (o *OrderCreateResponseOrdersInnerLinesInner) HasAdditionalAttributes() bool {
	if o != nil && !IsNil(o.AdditionalAttributes) {
		return true
	}

	return false
}

// SetAdditionalAttributes gets a reference to the given []OrderCreateResponseOrdersInnerLinesInnerAdditionalAttributesInner and assigns it to the AdditionalAttributes field.
func (o *OrderCreateResponseOrdersInnerLinesInner) SetAdditionalAttributes(v []OrderCreateResponseOrdersInnerLinesInnerAdditionalAttributesInner) {
	o.AdditionalAttributes = v
}

func (o OrderCreateResponseOrdersInnerLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateResponseOrdersInnerLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubOrderNumber) {
		toSerialize["subOrderNumber"] = o.SubOrderNumber
	}
	if !IsNil(o.IngramLineNumber) {
		toSerialize["ingramLineNumber"] = o.IngramLineNumber
	}
	if !IsNil(o.CustomerLineNumber) {
		toSerialize["customerLineNumber"] = o.CustomerLineNumber
	}
	if !IsNil(o.LineStatus) {
		toSerialize["lineStatus"] = o.LineStatus
	}
	if !IsNil(o.IngramPartNumber) {
		toSerialize["ingramPartNumber"] = o.IngramPartNumber
	}
	if !IsNil(o.VendorPartNumber) {
		toSerialize["vendorPartNumber"] = o.VendorPartNumber
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if !IsNil(o.ExtendedUnitPrice) {
		toSerialize["extendedUnitPrice"] = o.ExtendedUnitPrice
	}
	if !IsNil(o.QuantityOrdered) {
		toSerialize["quantityOrdered"] = o.QuantityOrdered
	}
	if !IsNil(o.QuantityConfirmed) {
		toSerialize["quantityConfirmed"] = o.QuantityConfirmed
	}
	if !IsNil(o.QuantityBackOrdered) {
		toSerialize["quantityBackOrdered"] = o.QuantityBackOrdered
	}
	if !IsNil(o.SpecialBidNumber) {
		toSerialize["specialBidNumber"] = o.SpecialBidNumber
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.ShipmentDetails) {
		toSerialize["shipmentDetails"] = o.ShipmentDetails
	}
	if !IsNil(o.AdditionalAttributes) {
		toSerialize["additionalAttributes"] = o.AdditionalAttributes
	}
	return toSerialize, nil
}

type NullableOrderCreateResponseOrdersInnerLinesInner struct {
	value *OrderCreateResponseOrdersInnerLinesInner
	isSet bool
}

func (v NullableOrderCreateResponseOrdersInnerLinesInner) Get() *OrderCreateResponseOrdersInnerLinesInner {
	return v.value
}

func (v *NullableOrderCreateResponseOrdersInnerLinesInner) Set(val *OrderCreateResponseOrdersInnerLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateResponseOrdersInnerLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateResponseOrdersInnerLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateResponseOrdersInnerLinesInner(val *OrderCreateResponseOrdersInnerLinesInner) *NullableOrderCreateResponseOrdersInnerLinesInner {
	return &NullableOrderCreateResponseOrdersInnerLinesInner{value: val, isSet: true}
}

func (v NullableOrderCreateResponseOrdersInnerLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateResponseOrdersInnerLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


