/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderDetailB2BLinesInnerScheduleLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDetailB2BLinesInnerScheduleLinesInner{}

// OrderDetailB2BLinesInnerScheduleLinesInner struct for OrderDetailB2BLinesInnerScheduleLinesInner
type OrderDetailB2BLinesInnerScheduleLinesInner struct {
	// Line number.
	LineNumber *string `json:"lineNumber,omitempty"`
	// schedule Line Date.
	ScheduleLineDate *string `json:"scheduleLineDate,omitempty"`
	// Requested quantity.
	RequestedQuantity *string `json:"requestedQuantity,omitempty"`
	// Confirmed quantity.
	ConfirmedQuantity *string `json:"confirmedQuantity,omitempty"`
	// Date when good issued.
	GoodsIssueDate *string `json:"goodsIssueDate,omitempty"`
}

// NewOrderDetailB2BLinesInnerScheduleLinesInner instantiates a new OrderDetailB2BLinesInnerScheduleLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDetailB2BLinesInnerScheduleLinesInner() *OrderDetailB2BLinesInnerScheduleLinesInner {
	this := OrderDetailB2BLinesInnerScheduleLinesInner{}
	return &this
}

// NewOrderDetailB2BLinesInnerScheduleLinesInnerWithDefaults instantiates a new OrderDetailB2BLinesInnerScheduleLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDetailB2BLinesInnerScheduleLinesInnerWithDefaults() *OrderDetailB2BLinesInnerScheduleLinesInner {
	this := OrderDetailB2BLinesInnerScheduleLinesInner{}
	return &this
}

// GetLineNumber returns the LineNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetLineNumber() string {
	if o == nil || IsNil(o.LineNumber) {
		var ret string
		return ret
	}
	return *o.LineNumber
}

// GetLineNumberOk returns a tuple with the LineNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetLineNumberOk() (*string, bool) {
	if o == nil || IsNil(o.LineNumber) {
		return nil, false
	}
	return o.LineNumber, true
}

// HasLineNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) HasLineNumber() bool {
	if o != nil && !IsNil(o.LineNumber) {
		return true
	}

	return false
}

// SetLineNumber gets a reference to the given string and assigns it to the LineNumber field.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) SetLineNumber(v string) {
	o.LineNumber = &v
}

// GetScheduleLineDate returns the ScheduleLineDate field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetScheduleLineDate() string {
	if o == nil || IsNil(o.ScheduleLineDate) {
		var ret string
		return ret
	}
	return *o.ScheduleLineDate
}

// GetScheduleLineDateOk returns a tuple with the ScheduleLineDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetScheduleLineDateOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduleLineDate) {
		return nil, false
	}
	return o.ScheduleLineDate, true
}

// HasScheduleLineDate returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) HasScheduleLineDate() bool {
	if o != nil && !IsNil(o.ScheduleLineDate) {
		return true
	}

	return false
}

// SetScheduleLineDate gets a reference to the given string and assigns it to the ScheduleLineDate field.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) SetScheduleLineDate(v string) {
	o.ScheduleLineDate = &v
}

// GetRequestedQuantity returns the RequestedQuantity field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetRequestedQuantity() string {
	if o == nil || IsNil(o.RequestedQuantity) {
		var ret string
		return ret
	}
	return *o.RequestedQuantity
}

// GetRequestedQuantityOk returns a tuple with the RequestedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetRequestedQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.RequestedQuantity) {
		return nil, false
	}
	return o.RequestedQuantity, true
}

// HasRequestedQuantity returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) HasRequestedQuantity() bool {
	if o != nil && !IsNil(o.RequestedQuantity) {
		return true
	}

	return false
}

// SetRequestedQuantity gets a reference to the given string and assigns it to the RequestedQuantity field.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) SetRequestedQuantity(v string) {
	o.RequestedQuantity = &v
}

// GetConfirmedQuantity returns the ConfirmedQuantity field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetConfirmedQuantity() string {
	if o == nil || IsNil(o.ConfirmedQuantity) {
		var ret string
		return ret
	}
	return *o.ConfirmedQuantity
}

// GetConfirmedQuantityOk returns a tuple with the ConfirmedQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetConfirmedQuantityOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmedQuantity) {
		return nil, false
	}
	return o.ConfirmedQuantity, true
}

// HasConfirmedQuantity returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) HasConfirmedQuantity() bool {
	if o != nil && !IsNil(o.ConfirmedQuantity) {
		return true
	}

	return false
}

// SetConfirmedQuantity gets a reference to the given string and assigns it to the ConfirmedQuantity field.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) SetConfirmedQuantity(v string) {
	o.ConfirmedQuantity = &v
}

// GetGoodsIssueDate returns the GoodsIssueDate field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetGoodsIssueDate() string {
	if o == nil || IsNil(o.GoodsIssueDate) {
		var ret string
		return ret
	}
	return *o.GoodsIssueDate
}

// GetGoodsIssueDateOk returns a tuple with the GoodsIssueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) GetGoodsIssueDateOk() (*string, bool) {
	if o == nil || IsNil(o.GoodsIssueDate) {
		return nil, false
	}
	return o.GoodsIssueDate, true
}

// HasGoodsIssueDate returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) HasGoodsIssueDate() bool {
	if o != nil && !IsNil(o.GoodsIssueDate) {
		return true
	}

	return false
}

// SetGoodsIssueDate gets a reference to the given string and assigns it to the GoodsIssueDate field.
func (o *OrderDetailB2BLinesInnerScheduleLinesInner) SetGoodsIssueDate(v string) {
	o.GoodsIssueDate = &v
}

func (o OrderDetailB2BLinesInnerScheduleLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDetailB2BLinesInnerScheduleLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LineNumber) {
		toSerialize["lineNumber"] = o.LineNumber
	}
	if !IsNil(o.ScheduleLineDate) {
		toSerialize["scheduleLineDate"] = o.ScheduleLineDate
	}
	if !IsNil(o.RequestedQuantity) {
		toSerialize["requestedQuantity"] = o.RequestedQuantity
	}
	if !IsNil(o.ConfirmedQuantity) {
		toSerialize["confirmedQuantity"] = o.ConfirmedQuantity
	}
	if !IsNil(o.GoodsIssueDate) {
		toSerialize["goodsIssueDate"] = o.GoodsIssueDate
	}
	return toSerialize, nil
}

type NullableOrderDetailB2BLinesInnerScheduleLinesInner struct {
	value *OrderDetailB2BLinesInnerScheduleLinesInner
	isSet bool
}

func (v NullableOrderDetailB2BLinesInnerScheduleLinesInner) Get() *OrderDetailB2BLinesInnerScheduleLinesInner {
	return v.value
}

func (v *NullableOrderDetailB2BLinesInnerScheduleLinesInner) Set(val *OrderDetailB2BLinesInnerScheduleLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDetailB2BLinesInnerScheduleLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDetailB2BLinesInnerScheduleLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDetailB2BLinesInnerScheduleLinesInner(val *OrderDetailB2BLinesInnerScheduleLinesInner) *NullableOrderDetailB2BLinesInnerScheduleLinesInner {
	return &NullableOrderDetailB2BLinesInnerScheduleLinesInner{value: val, isSet: true}
}

func (v NullableOrderDetailB2BLinesInnerScheduleLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDetailB2BLinesInnerScheduleLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


