/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro APIs solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderCreateV7RequestLinesInnerBillingPeriodInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateV7RequestLinesInnerBillingPeriodInner{}

// OrderCreateV7RequestLinesInnerBillingPeriodInner struct for OrderCreateV7RequestLinesInnerBillingPeriodInner
type OrderCreateV7RequestLinesInnerBillingPeriodInner struct {
	// Billing period of the subscription. Example, Years, Months
	Type *string `json:"type,omitempty"`
	// Length of the billing period. Example 1, 3
	Duration *int32 `json:"duration,omitempty"`
}

// NewOrderCreateV7RequestLinesInnerBillingPeriodInner instantiates a new OrderCreateV7RequestLinesInnerBillingPeriodInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateV7RequestLinesInnerBillingPeriodInner() *OrderCreateV7RequestLinesInnerBillingPeriodInner {
	this := OrderCreateV7RequestLinesInnerBillingPeriodInner{}
	return &this
}

// NewOrderCreateV7RequestLinesInnerBillingPeriodInnerWithDefaults instantiates a new OrderCreateV7RequestLinesInnerBillingPeriodInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateV7RequestLinesInnerBillingPeriodInnerWithDefaults() *OrderCreateV7RequestLinesInnerBillingPeriodInner {
	this := OrderCreateV7RequestLinesInnerBillingPeriodInner{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) SetType(v string) {
	o.Type = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *OrderCreateV7RequestLinesInnerBillingPeriodInner) SetDuration(v int32) {
	o.Duration = &v
}

func (o OrderCreateV7RequestLinesInnerBillingPeriodInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateV7RequestLinesInnerBillingPeriodInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

type NullableOrderCreateV7RequestLinesInnerBillingPeriodInner struct {
	value *OrderCreateV7RequestLinesInnerBillingPeriodInner
	isSet bool
}

func (v NullableOrderCreateV7RequestLinesInnerBillingPeriodInner) Get() *OrderCreateV7RequestLinesInnerBillingPeriodInner {
	return v.value
}

func (v *NullableOrderCreateV7RequestLinesInnerBillingPeriodInner) Set(val *OrderCreateV7RequestLinesInnerBillingPeriodInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateV7RequestLinesInnerBillingPeriodInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateV7RequestLinesInnerBillingPeriodInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateV7RequestLinesInnerBillingPeriodInner(val *OrderCreateV7RequestLinesInnerBillingPeriodInner) *NullableOrderCreateV7RequestLinesInnerBillingPeriodInner {
	return &NullableOrderCreateV7RequestLinesInnerBillingPeriodInner{value: val, isSet: true}
}

func (v NullableOrderCreateV7RequestLinesInnerBillingPeriodInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateV7RequestLinesInnerBillingPeriodInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


