/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderDetailB2BLinesInnerAdditionalAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDetailB2BLinesInnerAdditionalAttributesInner{}

// OrderDetailB2BLinesInnerAdditionalAttributesInner struct for OrderDetailB2BLinesInnerAdditionalAttributesInner
type OrderDetailB2BLinesInnerAdditionalAttributesInner struct {
	// Line level custom field names.
	AttributeName *string `json:"attributeName,omitempty"`
	// Value of the custom fields.
	AttributeValue *string `json:"attributeValue,omitempty"`
}

// NewOrderDetailB2BLinesInnerAdditionalAttributesInner instantiates a new OrderDetailB2BLinesInnerAdditionalAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDetailB2BLinesInnerAdditionalAttributesInner() *OrderDetailB2BLinesInnerAdditionalAttributesInner {
	this := OrderDetailB2BLinesInnerAdditionalAttributesInner{}
	return &this
}

// NewOrderDetailB2BLinesInnerAdditionalAttributesInnerWithDefaults instantiates a new OrderDetailB2BLinesInnerAdditionalAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDetailB2BLinesInnerAdditionalAttributesInnerWithDefaults() *OrderDetailB2BLinesInnerAdditionalAttributesInner {
	this := OrderDetailB2BLinesInnerAdditionalAttributesInner{}
	return &this
}

// GetAttributeName returns the AttributeName field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) GetAttributeName() string {
	if o == nil || IsNil(o.AttributeName) {
		var ret string
		return ret
	}
	return *o.AttributeName
}

// GetAttributeNameOk returns a tuple with the AttributeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) GetAttributeNameOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeName) {
		return nil, false
	}
	return o.AttributeName, true
}

// HasAttributeName returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) HasAttributeName() bool {
	if o != nil && !IsNil(o.AttributeName) {
		return true
	}

	return false
}

// SetAttributeName gets a reference to the given string and assigns it to the AttributeName field.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) SetAttributeName(v string) {
	o.AttributeName = &v
}

// GetAttributeValue returns the AttributeValue field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) GetAttributeValue() string {
	if o == nil || IsNil(o.AttributeValue) {
		var ret string
		return ret
	}
	return *o.AttributeValue
}

// GetAttributeValueOk returns a tuple with the AttributeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) GetAttributeValueOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeValue) {
		return nil, false
	}
	return o.AttributeValue, true
}

// HasAttributeValue returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) HasAttributeValue() bool {
	if o != nil && !IsNil(o.AttributeValue) {
		return true
	}

	return false
}

// SetAttributeValue gets a reference to the given string and assigns it to the AttributeValue field.
func (o *OrderDetailB2BLinesInnerAdditionalAttributesInner) SetAttributeValue(v string) {
	o.AttributeValue = &v
}

func (o OrderDetailB2BLinesInnerAdditionalAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDetailB2BLinesInnerAdditionalAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeName) {
		toSerialize["attributeName"] = o.AttributeName
	}
	if !IsNil(o.AttributeValue) {
		toSerialize["attributeValue"] = o.AttributeValue
	}
	return toSerialize, nil
}

type NullableOrderDetailB2BLinesInnerAdditionalAttributesInner struct {
	value *OrderDetailB2BLinesInnerAdditionalAttributesInner
	isSet bool
}

func (v NullableOrderDetailB2BLinesInnerAdditionalAttributesInner) Get() *OrderDetailB2BLinesInnerAdditionalAttributesInner {
	return v.value
}

func (v *NullableOrderDetailB2BLinesInnerAdditionalAttributesInner) Set(val *OrderDetailB2BLinesInnerAdditionalAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDetailB2BLinesInnerAdditionalAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDetailB2BLinesInnerAdditionalAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDetailB2BLinesInnerAdditionalAttributesInner(val *OrderDetailB2BLinesInnerAdditionalAttributesInner) *NullableOrderDetailB2BLinesInnerAdditionalAttributesInner {
	return &NullableOrderDetailB2BLinesInnerAdditionalAttributesInner{value: val, isSet: true}
}

func (v NullableOrderDetailB2BLinesInnerAdditionalAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDetailB2BLinesInnerAdditionalAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


