/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderDetailB2BLinesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderDetailB2BLinesInner{}

// OrderDetailB2BLinesInner struct for OrderDetailB2BLinesInner
type OrderDetailB2BLinesInner struct {
	// The sub order number. The two-digit prefix is the warehouse code of the warehouse nearest the reseller. The middle number is the order number. The two-digit suffix is the sub order number.
	SubOrderNumber *string `json:"subOrderNumber,omitempty"`
	// Unique Ingram Micro line number. Starts with 001.
	IngramOrderLineNumber *string `json:"ingramOrderLineNumber,omitempty"`
	// The vendor's sales order line number.
	VendorSalesOrderLineNumber *string `json:"vendorSalesOrderLineNumber,omitempty"`
	// The reseller's line item number for reference in their system.
	CustomerLineNumber *string `json:"customerLineNumber,omitempty"`
	// The status for the line item in the order. One of- Backordered, In Progress, Shipped, Delivered, Canceled, On Hold.
	LineStatus *string `json:"lineStatus,omitempty"`
	// Unique IngramMicro part number.
	IngramPartNumber *string `json:"ingramPartNumber,omitempty"`
	// The vendor's part number for the line item.
	VendorPartNumber *string `json:"vendorPartNumber,omitempty"`
	// The vendor's name for the part in their system.
	VendorName *string `json:"vendorName,omitempty"`
	// The vendor's description of the part in their system.
	PartDescription *string `json:"partDescription,omitempty"`
	// The unit weight of the line item.
	UnitWeight *float64 `json:"unitWeight,omitempty"`
	// The unit of measure for the line item.
	WeightUom *string `json:"weightUom,omitempty"`
	// The unit price of the line item.
	UnitPrice *float64 `json:"unitPrice,omitempty"`
	// The UPC code of a product.
	UpcCode *string `json:"upcCode,omitempty"`
	// Unit price X quantity for the line item.
	ExtendedPrice *float64 `json:"extendedPrice,omitempty"`
	// The tax amount for the line item.
	TaxAmount *float64 `json:"taxAmount,omitempty"`
	// The country-specific three character ISO 4217 currency code for the line item.
	CurrencyCode *string `json:"currencyCode,omitempty"`
	// The quantity ordered of the line item.
	QuantityOrdered *int32 `json:"quantityOrdered,omitempty"`
	// The quantity confirmed for the line item.
	QuantityConfirmed *int32 `json:"quantityConfirmed,omitempty"`
	// The quantity backordered for the line item.
	QuantityBackOrdered *int32 `json:"quantityBackOrdered,omitempty"`
	// The line-level bid number provided to the reseller by the vendor for special pricing and discounts. Used to track the bid number in the case of split orders or where different line items have different bid numbers. Line-level bid numbers take precedence over header-level bid numbers.
	SpecialBidNumber *string `json:"specialBidNumber,omitempty"`
	// Reseller-requested delivery date. Delivery date is not guaranteed.
	RequestedDeliverydate *string `json:"requestedDeliverydate,omitempty"`
	// The delivery date promised by IngramMicro.
	PromisedDeliveryDate *string `json:"promisedDeliveryDate,omitempty"`
	// Backorder ETA date
	BackOrderETADate *string `json:"backOrderETADate,omitempty"`
	// Line-level notes for the order.
	LineNotes *string `json:"lineNotes,omitempty"`
	// Shipping details for the line item.
	ShipmentDetails []OrderDetailB2BLinesInnerShipmentDetailsInner `json:"shipmentDetails,omitempty"`
	ServiceContractInfo *OrderDetailB2BLinesInnerServiceContractInfo `json:"serviceContractInfo,omitempty"`
	AdditionalAttributes []OrderDetailB2BLinesInnerAdditionalAttributesInner `json:"additionalAttributes,omitempty"`
	Links []OrderDetailB2BLinesInnerLinksInner `json:"links,omitempty"`
	EstimatedDates []OrderDetailB2BLinesInnerEstimatedDatesInner `json:"estimatedDates,omitempty"`
	ScheduleLines []OrderDetailB2BLinesInnerScheduleLinesInner `json:"scheduleLines,omitempty"`
	MultipleShipments []OrderDetailB2BLinesInnerMultipleShipmentsInner `json:"multipleShipments,omitempty"`
	DefaultCarrierName *string `json:"defaultCarrierName,omitempty"`
}

// NewOrderDetailB2BLinesInner instantiates a new OrderDetailB2BLinesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderDetailB2BLinesInner() *OrderDetailB2BLinesInner {
	this := OrderDetailB2BLinesInner{}
	return &this
}

// NewOrderDetailB2BLinesInnerWithDefaults instantiates a new OrderDetailB2BLinesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderDetailB2BLinesInnerWithDefaults() *OrderDetailB2BLinesInner {
	this := OrderDetailB2BLinesInner{}
	return &this
}

// GetSubOrderNumber returns the SubOrderNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetSubOrderNumber() string {
	if o == nil || IsNil(o.SubOrderNumber) {
		var ret string
		return ret
	}
	return *o.SubOrderNumber
}

// GetSubOrderNumberOk returns a tuple with the SubOrderNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetSubOrderNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SubOrderNumber) {
		return nil, false
	}
	return o.SubOrderNumber, true
}

// HasSubOrderNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasSubOrderNumber() bool {
	if o != nil && !IsNil(o.SubOrderNumber) {
		return true
	}

	return false
}

// SetSubOrderNumber gets a reference to the given string and assigns it to the SubOrderNumber field.
func (o *OrderDetailB2BLinesInner) SetSubOrderNumber(v string) {
	o.SubOrderNumber = &v
}

// GetIngramOrderLineNumber returns the IngramOrderLineNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetIngramOrderLineNumber() string {
	if o == nil || IsNil(o.IngramOrderLineNumber) {
		var ret string
		return ret
	}
	return *o.IngramOrderLineNumber
}

// GetIngramOrderLineNumberOk returns a tuple with the IngramOrderLineNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetIngramOrderLineNumberOk() (*string, bool) {
	if o == nil || IsNil(o.IngramOrderLineNumber) {
		return nil, false
	}
	return o.IngramOrderLineNumber, true
}

// HasIngramOrderLineNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasIngramOrderLineNumber() bool {
	if o != nil && !IsNil(o.IngramOrderLineNumber) {
		return true
	}

	return false
}

// SetIngramOrderLineNumber gets a reference to the given string and assigns it to the IngramOrderLineNumber field.
func (o *OrderDetailB2BLinesInner) SetIngramOrderLineNumber(v string) {
	o.IngramOrderLineNumber = &v
}

// GetVendorSalesOrderLineNumber returns the VendorSalesOrderLineNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetVendorSalesOrderLineNumber() string {
	if o == nil || IsNil(o.VendorSalesOrderLineNumber) {
		var ret string
		return ret
	}
	return *o.VendorSalesOrderLineNumber
}

// GetVendorSalesOrderLineNumberOk returns a tuple with the VendorSalesOrderLineNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetVendorSalesOrderLineNumberOk() (*string, bool) {
	if o == nil || IsNil(o.VendorSalesOrderLineNumber) {
		return nil, false
	}
	return o.VendorSalesOrderLineNumber, true
}

// HasVendorSalesOrderLineNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasVendorSalesOrderLineNumber() bool {
	if o != nil && !IsNil(o.VendorSalesOrderLineNumber) {
		return true
	}

	return false
}

// SetVendorSalesOrderLineNumber gets a reference to the given string and assigns it to the VendorSalesOrderLineNumber field.
func (o *OrderDetailB2BLinesInner) SetVendorSalesOrderLineNumber(v string) {
	o.VendorSalesOrderLineNumber = &v
}

// GetCustomerLineNumber returns the CustomerLineNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetCustomerLineNumber() string {
	if o == nil || IsNil(o.CustomerLineNumber) {
		var ret string
		return ret
	}
	return *o.CustomerLineNumber
}

// GetCustomerLineNumberOk returns a tuple with the CustomerLineNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetCustomerLineNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerLineNumber) {
		return nil, false
	}
	return o.CustomerLineNumber, true
}

// HasCustomerLineNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasCustomerLineNumber() bool {
	if o != nil && !IsNil(o.CustomerLineNumber) {
		return true
	}

	return false
}

// SetCustomerLineNumber gets a reference to the given string and assigns it to the CustomerLineNumber field.
func (o *OrderDetailB2BLinesInner) SetCustomerLineNumber(v string) {
	o.CustomerLineNumber = &v
}

// GetLineStatus returns the LineStatus field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetLineStatus() string {
	if o == nil || IsNil(o.LineStatus) {
		var ret string
		return ret
	}
	return *o.LineStatus
}

// GetLineStatusOk returns a tuple with the LineStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetLineStatusOk() (*string, bool) {
	if o == nil || IsNil(o.LineStatus) {
		return nil, false
	}
	return o.LineStatus, true
}

// HasLineStatus returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasLineStatus() bool {
	if o != nil && !IsNil(o.LineStatus) {
		return true
	}

	return false
}

// SetLineStatus gets a reference to the given string and assigns it to the LineStatus field.
func (o *OrderDetailB2BLinesInner) SetLineStatus(v string) {
	o.LineStatus = &v
}

// GetIngramPartNumber returns the IngramPartNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetIngramPartNumber() string {
	if o == nil || IsNil(o.IngramPartNumber) {
		var ret string
		return ret
	}
	return *o.IngramPartNumber
}

// GetIngramPartNumberOk returns a tuple with the IngramPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetIngramPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.IngramPartNumber) {
		return nil, false
	}
	return o.IngramPartNumber, true
}

// HasIngramPartNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasIngramPartNumber() bool {
	if o != nil && !IsNil(o.IngramPartNumber) {
		return true
	}

	return false
}

// SetIngramPartNumber gets a reference to the given string and assigns it to the IngramPartNumber field.
func (o *OrderDetailB2BLinesInner) SetIngramPartNumber(v string) {
	o.IngramPartNumber = &v
}

// GetVendorPartNumber returns the VendorPartNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetVendorPartNumber() string {
	if o == nil || IsNil(o.VendorPartNumber) {
		var ret string
		return ret
	}
	return *o.VendorPartNumber
}

// GetVendorPartNumberOk returns a tuple with the VendorPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetVendorPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.VendorPartNumber) {
		return nil, false
	}
	return o.VendorPartNumber, true
}

// HasVendorPartNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasVendorPartNumber() bool {
	if o != nil && !IsNil(o.VendorPartNumber) {
		return true
	}

	return false
}

// SetVendorPartNumber gets a reference to the given string and assigns it to the VendorPartNumber field.
func (o *OrderDetailB2BLinesInner) SetVendorPartNumber(v string) {
	o.VendorPartNumber = &v
}

// GetVendorName returns the VendorName field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetVendorName() string {
	if o == nil || IsNil(o.VendorName) {
		var ret string
		return ret
	}
	return *o.VendorName
}

// GetVendorNameOk returns a tuple with the VendorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetVendorNameOk() (*string, bool) {
	if o == nil || IsNil(o.VendorName) {
		return nil, false
	}
	return o.VendorName, true
}

// HasVendorName returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasVendorName() bool {
	if o != nil && !IsNil(o.VendorName) {
		return true
	}

	return false
}

// SetVendorName gets a reference to the given string and assigns it to the VendorName field.
func (o *OrderDetailB2BLinesInner) SetVendorName(v string) {
	o.VendorName = &v
}

// GetPartDescription returns the PartDescription field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetPartDescription() string {
	if o == nil || IsNil(o.PartDescription) {
		var ret string
		return ret
	}
	return *o.PartDescription
}

// GetPartDescriptionOk returns a tuple with the PartDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetPartDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.PartDescription) {
		return nil, false
	}
	return o.PartDescription, true
}

// HasPartDescription returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasPartDescription() bool {
	if o != nil && !IsNil(o.PartDescription) {
		return true
	}

	return false
}

// SetPartDescription gets a reference to the given string and assigns it to the PartDescription field.
func (o *OrderDetailB2BLinesInner) SetPartDescription(v string) {
	o.PartDescription = &v
}

// GetUnitWeight returns the UnitWeight field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetUnitWeight() float64 {
	if o == nil || IsNil(o.UnitWeight) {
		var ret float64
		return ret
	}
	return *o.UnitWeight
}

// GetUnitWeightOk returns a tuple with the UnitWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetUnitWeightOk() (*float64, bool) {
	if o == nil || IsNil(o.UnitWeight) {
		return nil, false
	}
	return o.UnitWeight, true
}

// HasUnitWeight returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasUnitWeight() bool {
	if o != nil && !IsNil(o.UnitWeight) {
		return true
	}

	return false
}

// SetUnitWeight gets a reference to the given float64 and assigns it to the UnitWeight field.
func (o *OrderDetailB2BLinesInner) SetUnitWeight(v float64) {
	o.UnitWeight = &v
}

// GetWeightUom returns the WeightUom field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetWeightUom() string {
	if o == nil || IsNil(o.WeightUom) {
		var ret string
		return ret
	}
	return *o.WeightUom
}

// GetWeightUomOk returns a tuple with the WeightUom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetWeightUomOk() (*string, bool) {
	if o == nil || IsNil(o.WeightUom) {
		return nil, false
	}
	return o.WeightUom, true
}

// HasWeightUom returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasWeightUom() bool {
	if o != nil && !IsNil(o.WeightUom) {
		return true
	}

	return false
}

// SetWeightUom gets a reference to the given string and assigns it to the WeightUom field.
func (o *OrderDetailB2BLinesInner) SetWeightUom(v string) {
	o.WeightUom = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetUnitPrice() float64 {
	if o == nil || IsNil(o.UnitPrice) {
		var ret float64
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetUnitPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given float64 and assigns it to the UnitPrice field.
func (o *OrderDetailB2BLinesInner) SetUnitPrice(v float64) {
	o.UnitPrice = &v
}

// GetUpcCode returns the UpcCode field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetUpcCode() string {
	if o == nil || IsNil(o.UpcCode) {
		var ret string
		return ret
	}
	return *o.UpcCode
}

// GetUpcCodeOk returns a tuple with the UpcCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetUpcCodeOk() (*string, bool) {
	if o == nil || IsNil(o.UpcCode) {
		return nil, false
	}
	return o.UpcCode, true
}

// HasUpcCode returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasUpcCode() bool {
	if o != nil && !IsNil(o.UpcCode) {
		return true
	}

	return false
}

// SetUpcCode gets a reference to the given string and assigns it to the UpcCode field.
func (o *OrderDetailB2BLinesInner) SetUpcCode(v string) {
	o.UpcCode = &v
}

// GetExtendedPrice returns the ExtendedPrice field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetExtendedPrice() float64 {
	if o == nil || IsNil(o.ExtendedPrice) {
		var ret float64
		return ret
	}
	return *o.ExtendedPrice
}

// GetExtendedPriceOk returns a tuple with the ExtendedPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetExtendedPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.ExtendedPrice) {
		return nil, false
	}
	return o.ExtendedPrice, true
}

// HasExtendedPrice returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasExtendedPrice() bool {
	if o != nil && !IsNil(o.ExtendedPrice) {
		return true
	}

	return false
}

// SetExtendedPrice gets a reference to the given float64 and assigns it to the ExtendedPrice field.
func (o *OrderDetailB2BLinesInner) SetExtendedPrice(v float64) {
	o.ExtendedPrice = &v
}

// GetTaxAmount returns the TaxAmount field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetTaxAmount() float64 {
	if o == nil || IsNil(o.TaxAmount) {
		var ret float64
		return ret
	}
	return *o.TaxAmount
}

// GetTaxAmountOk returns a tuple with the TaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetTaxAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.TaxAmount) {
		return nil, false
	}
	return o.TaxAmount, true
}

// HasTaxAmount returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasTaxAmount() bool {
	if o != nil && !IsNil(o.TaxAmount) {
		return true
	}

	return false
}

// SetTaxAmount gets a reference to the given float64 and assigns it to the TaxAmount field.
func (o *OrderDetailB2BLinesInner) SetTaxAmount(v float64) {
	o.TaxAmount = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *OrderDetailB2BLinesInner) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetQuantityOrdered returns the QuantityOrdered field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetQuantityOrdered() int32 {
	if o == nil || IsNil(o.QuantityOrdered) {
		var ret int32
		return ret
	}
	return *o.QuantityOrdered
}

// GetQuantityOrderedOk returns a tuple with the QuantityOrdered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetQuantityOrderedOk() (*int32, bool) {
	if o == nil || IsNil(o.QuantityOrdered) {
		return nil, false
	}
	return o.QuantityOrdered, true
}

// HasQuantityOrdered returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasQuantityOrdered() bool {
	if o != nil && !IsNil(o.QuantityOrdered) {
		return true
	}

	return false
}

// SetQuantityOrdered gets a reference to the given int32 and assigns it to the QuantityOrdered field.
func (o *OrderDetailB2BLinesInner) SetQuantityOrdered(v int32) {
	o.QuantityOrdered = &v
}

// GetQuantityConfirmed returns the QuantityConfirmed field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetQuantityConfirmed() int32 {
	if o == nil || IsNil(o.QuantityConfirmed) {
		var ret int32
		return ret
	}
	return *o.QuantityConfirmed
}

// GetQuantityConfirmedOk returns a tuple with the QuantityConfirmed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetQuantityConfirmedOk() (*int32, bool) {
	if o == nil || IsNil(o.QuantityConfirmed) {
		return nil, false
	}
	return o.QuantityConfirmed, true
}

// HasQuantityConfirmed returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasQuantityConfirmed() bool {
	if o != nil && !IsNil(o.QuantityConfirmed) {
		return true
	}

	return false
}

// SetQuantityConfirmed gets a reference to the given int32 and assigns it to the QuantityConfirmed field.
func (o *OrderDetailB2BLinesInner) SetQuantityConfirmed(v int32) {
	o.QuantityConfirmed = &v
}

// GetQuantityBackOrdered returns the QuantityBackOrdered field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetQuantityBackOrdered() int32 {
	if o == nil || IsNil(o.QuantityBackOrdered) {
		var ret int32
		return ret
	}
	return *o.QuantityBackOrdered
}

// GetQuantityBackOrderedOk returns a tuple with the QuantityBackOrdered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetQuantityBackOrderedOk() (*int32, bool) {
	if o == nil || IsNil(o.QuantityBackOrdered) {
		return nil, false
	}
	return o.QuantityBackOrdered, true
}

// HasQuantityBackOrdered returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasQuantityBackOrdered() bool {
	if o != nil && !IsNil(o.QuantityBackOrdered) {
		return true
	}

	return false
}

// SetQuantityBackOrdered gets a reference to the given int32 and assigns it to the QuantityBackOrdered field.
func (o *OrderDetailB2BLinesInner) SetQuantityBackOrdered(v int32) {
	o.QuantityBackOrdered = &v
}

// GetSpecialBidNumber returns the SpecialBidNumber field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetSpecialBidNumber() string {
	if o == nil || IsNil(o.SpecialBidNumber) {
		var ret string
		return ret
	}
	return *o.SpecialBidNumber
}

// GetSpecialBidNumberOk returns a tuple with the SpecialBidNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetSpecialBidNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SpecialBidNumber) {
		return nil, false
	}
	return o.SpecialBidNumber, true
}

// HasSpecialBidNumber returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasSpecialBidNumber() bool {
	if o != nil && !IsNil(o.SpecialBidNumber) {
		return true
	}

	return false
}

// SetSpecialBidNumber gets a reference to the given string and assigns it to the SpecialBidNumber field.
func (o *OrderDetailB2BLinesInner) SetSpecialBidNumber(v string) {
	o.SpecialBidNumber = &v
}

// GetRequestedDeliverydate returns the RequestedDeliverydate field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetRequestedDeliverydate() string {
	if o == nil || IsNil(o.RequestedDeliverydate) {
		var ret string
		return ret
	}
	return *o.RequestedDeliverydate
}

// GetRequestedDeliverydateOk returns a tuple with the RequestedDeliverydate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetRequestedDeliverydateOk() (*string, bool) {
	if o == nil || IsNil(o.RequestedDeliverydate) {
		return nil, false
	}
	return o.RequestedDeliverydate, true
}

// HasRequestedDeliverydate returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasRequestedDeliverydate() bool {
	if o != nil && !IsNil(o.RequestedDeliverydate) {
		return true
	}

	return false
}

// SetRequestedDeliverydate gets a reference to the given string and assigns it to the RequestedDeliverydate field.
func (o *OrderDetailB2BLinesInner) SetRequestedDeliverydate(v string) {
	o.RequestedDeliverydate = &v
}

// GetPromisedDeliveryDate returns the PromisedDeliveryDate field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetPromisedDeliveryDate() string {
	if o == nil || IsNil(o.PromisedDeliveryDate) {
		var ret string
		return ret
	}
	return *o.PromisedDeliveryDate
}

// GetPromisedDeliveryDateOk returns a tuple with the PromisedDeliveryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetPromisedDeliveryDateOk() (*string, bool) {
	if o == nil || IsNil(o.PromisedDeliveryDate) {
		return nil, false
	}
	return o.PromisedDeliveryDate, true
}

// HasPromisedDeliveryDate returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasPromisedDeliveryDate() bool {
	if o != nil && !IsNil(o.PromisedDeliveryDate) {
		return true
	}

	return false
}

// SetPromisedDeliveryDate gets a reference to the given string and assigns it to the PromisedDeliveryDate field.
func (o *OrderDetailB2BLinesInner) SetPromisedDeliveryDate(v string) {
	o.PromisedDeliveryDate = &v
}

// GetBackOrderETADate returns the BackOrderETADate field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetBackOrderETADate() string {
	if o == nil || IsNil(o.BackOrderETADate) {
		var ret string
		return ret
	}
	return *o.BackOrderETADate
}

// GetBackOrderETADateOk returns a tuple with the BackOrderETADate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetBackOrderETADateOk() (*string, bool) {
	if o == nil || IsNil(o.BackOrderETADate) {
		return nil, false
	}
	return o.BackOrderETADate, true
}

// HasBackOrderETADate returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasBackOrderETADate() bool {
	if o != nil && !IsNil(o.BackOrderETADate) {
		return true
	}

	return false
}

// SetBackOrderETADate gets a reference to the given string and assigns it to the BackOrderETADate field.
func (o *OrderDetailB2BLinesInner) SetBackOrderETADate(v string) {
	o.BackOrderETADate = &v
}

// GetLineNotes returns the LineNotes field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetLineNotes() string {
	if o == nil || IsNil(o.LineNotes) {
		var ret string
		return ret
	}
	return *o.LineNotes
}

// GetLineNotesOk returns a tuple with the LineNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetLineNotesOk() (*string, bool) {
	if o == nil || IsNil(o.LineNotes) {
		return nil, false
	}
	return o.LineNotes, true
}

// HasLineNotes returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasLineNotes() bool {
	if o != nil && !IsNil(o.LineNotes) {
		return true
	}

	return false
}

// SetLineNotes gets a reference to the given string and assigns it to the LineNotes field.
func (o *OrderDetailB2BLinesInner) SetLineNotes(v string) {
	o.LineNotes = &v
}

// GetShipmentDetails returns the ShipmentDetails field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderDetailB2BLinesInner) GetShipmentDetails() []OrderDetailB2BLinesInnerShipmentDetailsInner {
	if o == nil {
		var ret []OrderDetailB2BLinesInnerShipmentDetailsInner
		return ret
	}
	return o.ShipmentDetails
}

// GetShipmentDetailsOk returns a tuple with the ShipmentDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderDetailB2BLinesInner) GetShipmentDetailsOk() ([]OrderDetailB2BLinesInnerShipmentDetailsInner, bool) {
	if o == nil || IsNil(o.ShipmentDetails) {
		return nil, false
	}
	return o.ShipmentDetails, true
}

// HasShipmentDetails returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasShipmentDetails() bool {
	if o != nil && !IsNil(o.ShipmentDetails) {
		return true
	}

	return false
}

// SetShipmentDetails gets a reference to the given []OrderDetailB2BLinesInnerShipmentDetailsInner and assigns it to the ShipmentDetails field.
func (o *OrderDetailB2BLinesInner) SetShipmentDetails(v []OrderDetailB2BLinesInnerShipmentDetailsInner) {
	o.ShipmentDetails = v
}

// GetServiceContractInfo returns the ServiceContractInfo field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetServiceContractInfo() OrderDetailB2BLinesInnerServiceContractInfo {
	if o == nil || IsNil(o.ServiceContractInfo) {
		var ret OrderDetailB2BLinesInnerServiceContractInfo
		return ret
	}
	return *o.ServiceContractInfo
}

// GetServiceContractInfoOk returns a tuple with the ServiceContractInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetServiceContractInfoOk() (*OrderDetailB2BLinesInnerServiceContractInfo, bool) {
	if o == nil || IsNil(o.ServiceContractInfo) {
		return nil, false
	}
	return o.ServiceContractInfo, true
}

// HasServiceContractInfo returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasServiceContractInfo() bool {
	if o != nil && !IsNil(o.ServiceContractInfo) {
		return true
	}

	return false
}

// SetServiceContractInfo gets a reference to the given OrderDetailB2BLinesInnerServiceContractInfo and assigns it to the ServiceContractInfo field.
func (o *OrderDetailB2BLinesInner) SetServiceContractInfo(v OrderDetailB2BLinesInnerServiceContractInfo) {
	o.ServiceContractInfo = &v
}

// GetAdditionalAttributes returns the AdditionalAttributes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderDetailB2BLinesInner) GetAdditionalAttributes() []OrderDetailB2BLinesInnerAdditionalAttributesInner {
	if o == nil {
		var ret []OrderDetailB2BLinesInnerAdditionalAttributesInner
		return ret
	}
	return o.AdditionalAttributes
}

// GetAdditionalAttributesOk returns a tuple with the AdditionalAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderDetailB2BLinesInner) GetAdditionalAttributesOk() ([]OrderDetailB2BLinesInnerAdditionalAttributesInner, bool) {
	if o == nil || IsNil(o.AdditionalAttributes) {
		return nil, false
	}
	return o.AdditionalAttributes, true
}

// HasAdditionalAttributes returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasAdditionalAttributes() bool {
	if o != nil && !IsNil(o.AdditionalAttributes) {
		return true
	}

	return false
}

// SetAdditionalAttributes gets a reference to the given []OrderDetailB2BLinesInnerAdditionalAttributesInner and assigns it to the AdditionalAttributes field.
func (o *OrderDetailB2BLinesInner) SetAdditionalAttributes(v []OrderDetailB2BLinesInnerAdditionalAttributesInner) {
	o.AdditionalAttributes = v
}

// GetLinks returns the Links field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderDetailB2BLinesInner) GetLinks() []OrderDetailB2BLinesInnerLinksInner {
	if o == nil {
		var ret []OrderDetailB2BLinesInnerLinksInner
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderDetailB2BLinesInner) GetLinksOk() ([]OrderDetailB2BLinesInnerLinksInner, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []OrderDetailB2BLinesInnerLinksInner and assigns it to the Links field.
func (o *OrderDetailB2BLinesInner) SetLinks(v []OrderDetailB2BLinesInnerLinksInner) {
	o.Links = v
}

// GetEstimatedDates returns the EstimatedDates field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetEstimatedDates() []OrderDetailB2BLinesInnerEstimatedDatesInner {
	if o == nil || IsNil(o.EstimatedDates) {
		var ret []OrderDetailB2BLinesInnerEstimatedDatesInner
		return ret
	}
	return o.EstimatedDates
}

// GetEstimatedDatesOk returns a tuple with the EstimatedDates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetEstimatedDatesOk() ([]OrderDetailB2BLinesInnerEstimatedDatesInner, bool) {
	if o == nil || IsNil(o.EstimatedDates) {
		return nil, false
	}
	return o.EstimatedDates, true
}

// HasEstimatedDates returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasEstimatedDates() bool {
	if o != nil && !IsNil(o.EstimatedDates) {
		return true
	}

	return false
}

// SetEstimatedDates gets a reference to the given []OrderDetailB2BLinesInnerEstimatedDatesInner and assigns it to the EstimatedDates field.
func (o *OrderDetailB2BLinesInner) SetEstimatedDates(v []OrderDetailB2BLinesInnerEstimatedDatesInner) {
	o.EstimatedDates = v
}

// GetScheduleLines returns the ScheduleLines field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetScheduleLines() []OrderDetailB2BLinesInnerScheduleLinesInner {
	if o == nil || IsNil(o.ScheduleLines) {
		var ret []OrderDetailB2BLinesInnerScheduleLinesInner
		return ret
	}
	return o.ScheduleLines
}

// GetScheduleLinesOk returns a tuple with the ScheduleLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetScheduleLinesOk() ([]OrderDetailB2BLinesInnerScheduleLinesInner, bool) {
	if o == nil || IsNil(o.ScheduleLines) {
		return nil, false
	}
	return o.ScheduleLines, true
}

// HasScheduleLines returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasScheduleLines() bool {
	if o != nil && !IsNil(o.ScheduleLines) {
		return true
	}

	return false
}

// SetScheduleLines gets a reference to the given []OrderDetailB2BLinesInnerScheduleLinesInner and assigns it to the ScheduleLines field.
func (o *OrderDetailB2BLinesInner) SetScheduleLines(v []OrderDetailB2BLinesInnerScheduleLinesInner) {
	o.ScheduleLines = v
}

// GetMultipleShipments returns the MultipleShipments field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetMultipleShipments() []OrderDetailB2BLinesInnerMultipleShipmentsInner {
	if o == nil || IsNil(o.MultipleShipments) {
		var ret []OrderDetailB2BLinesInnerMultipleShipmentsInner
		return ret
	}
	return o.MultipleShipments
}

// GetMultipleShipmentsOk returns a tuple with the MultipleShipments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetMultipleShipmentsOk() ([]OrderDetailB2BLinesInnerMultipleShipmentsInner, bool) {
	if o == nil || IsNil(o.MultipleShipments) {
		return nil, false
	}
	return o.MultipleShipments, true
}

// HasMultipleShipments returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasMultipleShipments() bool {
	if o != nil && !IsNil(o.MultipleShipments) {
		return true
	}

	return false
}

// SetMultipleShipments gets a reference to the given []OrderDetailB2BLinesInnerMultipleShipmentsInner and assigns it to the MultipleShipments field.
func (o *OrderDetailB2BLinesInner) SetMultipleShipments(v []OrderDetailB2BLinesInnerMultipleShipmentsInner) {
	o.MultipleShipments = v
}

// GetDefaultCarrierName returns the DefaultCarrierName field value if set, zero value otherwise.
func (o *OrderDetailB2BLinesInner) GetDefaultCarrierName() string {
	if o == nil || IsNil(o.DefaultCarrierName) {
		var ret string
		return ret
	}
	return *o.DefaultCarrierName
}

// GetDefaultCarrierNameOk returns a tuple with the DefaultCarrierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderDetailB2BLinesInner) GetDefaultCarrierNameOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCarrierName) {
		return nil, false
	}
	return o.DefaultCarrierName, true
}

// HasDefaultCarrierName returns a boolean if a field has been set.
func (o *OrderDetailB2BLinesInner) HasDefaultCarrierName() bool {
	if o != nil && !IsNil(o.DefaultCarrierName) {
		return true
	}

	return false
}

// SetDefaultCarrierName gets a reference to the given string and assigns it to the DefaultCarrierName field.
func (o *OrderDetailB2BLinesInner) SetDefaultCarrierName(v string) {
	o.DefaultCarrierName = &v
}

func (o OrderDetailB2BLinesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderDetailB2BLinesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SubOrderNumber) {
		toSerialize["subOrderNumber"] = o.SubOrderNumber
	}
	if !IsNil(o.IngramOrderLineNumber) {
		toSerialize["ingramOrderLineNumber"] = o.IngramOrderLineNumber
	}
	if !IsNil(o.VendorSalesOrderLineNumber) {
		toSerialize["vendorSalesOrderLineNumber"] = o.VendorSalesOrderLineNumber
	}
	if !IsNil(o.CustomerLineNumber) {
		toSerialize["customerLineNumber"] = o.CustomerLineNumber
	}
	if !IsNil(o.LineStatus) {
		toSerialize["lineStatus"] = o.LineStatus
	}
	if !IsNil(o.IngramPartNumber) {
		toSerialize["ingramPartNumber"] = o.IngramPartNumber
	}
	if !IsNil(o.VendorPartNumber) {
		toSerialize["vendorPartNumber"] = o.VendorPartNumber
	}
	if !IsNil(o.VendorName) {
		toSerialize["vendorName"] = o.VendorName
	}
	if !IsNil(o.PartDescription) {
		toSerialize["partDescription"] = o.PartDescription
	}
	if !IsNil(o.UnitWeight) {
		toSerialize["unitWeight"] = o.UnitWeight
	}
	if !IsNil(o.WeightUom) {
		toSerialize["weightUom"] = o.WeightUom
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if !IsNil(o.UpcCode) {
		toSerialize["upcCode"] = o.UpcCode
	}
	if !IsNil(o.ExtendedPrice) {
		toSerialize["extendedPrice"] = o.ExtendedPrice
	}
	if !IsNil(o.TaxAmount) {
		toSerialize["taxAmount"] = o.TaxAmount
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	if !IsNil(o.QuantityOrdered) {
		toSerialize["quantityOrdered"] = o.QuantityOrdered
	}
	if !IsNil(o.QuantityConfirmed) {
		toSerialize["quantityConfirmed"] = o.QuantityConfirmed
	}
	if !IsNil(o.QuantityBackOrdered) {
		toSerialize["quantityBackOrdered"] = o.QuantityBackOrdered
	}
	if !IsNil(o.SpecialBidNumber) {
		toSerialize["specialBidNumber"] = o.SpecialBidNumber
	}
	if !IsNil(o.RequestedDeliverydate) {
		toSerialize["requestedDeliverydate"] = o.RequestedDeliverydate
	}
	if !IsNil(o.PromisedDeliveryDate) {
		toSerialize["promisedDeliveryDate"] = o.PromisedDeliveryDate
	}
	if !IsNil(o.BackOrderETADate) {
		toSerialize["backOrderETADate"] = o.BackOrderETADate
	}
	if !IsNil(o.LineNotes) {
		toSerialize["lineNotes"] = o.LineNotes
	}
	if o.ShipmentDetails != nil {
		toSerialize["shipmentDetails"] = o.ShipmentDetails
	}
	if !IsNil(o.ServiceContractInfo) {
		toSerialize["serviceContractInfo"] = o.ServiceContractInfo
	}
	if o.AdditionalAttributes != nil {
		toSerialize["additionalAttributes"] = o.AdditionalAttributes
	}
	if o.Links != nil {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.EstimatedDates) {
		toSerialize["estimatedDates"] = o.EstimatedDates
	}
	if !IsNil(o.ScheduleLines) {
		toSerialize["scheduleLines"] = o.ScheduleLines
	}
	if !IsNil(o.MultipleShipments) {
		toSerialize["multipleShipments"] = o.MultipleShipments
	}
	if !IsNil(o.DefaultCarrierName) {
		toSerialize["defaultCarrierName"] = o.DefaultCarrierName
	}
	return toSerialize, nil
}

type NullableOrderDetailB2BLinesInner struct {
	value *OrderDetailB2BLinesInner
	isSet bool
}

func (v NullableOrderDetailB2BLinesInner) Get() *OrderDetailB2BLinesInner {
	return v.value
}

func (v *NullableOrderDetailB2BLinesInner) Set(val *OrderDetailB2BLinesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderDetailB2BLinesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderDetailB2BLinesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderDetailB2BLinesInner(val *OrderDetailB2BLinesInner) *NullableOrderDetailB2BLinesInner {
	return &NullableOrderDetailB2BLinesInner{value: val, isSet: true}
}

func (v NullableOrderDetailB2BLinesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderDetailB2BLinesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


