/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the OrderModifyResponseLinesInnerAdditionalAttributesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderModifyResponseLinesInnerAdditionalAttributesInner{}

// OrderModifyResponseLinesInnerAdditionalAttributesInner struct for OrderModifyResponseLinesInnerAdditionalAttributesInner
type OrderModifyResponseLinesInnerAdditionalAttributesInner struct {
	// Attribute Name.
	AttributeName *string `json:"attributeName,omitempty"`
	// Attribute Value.
	AttributeValue *string `json:"attributeValue,omitempty"`
}

// NewOrderModifyResponseLinesInnerAdditionalAttributesInner instantiates a new OrderModifyResponseLinesInnerAdditionalAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderModifyResponseLinesInnerAdditionalAttributesInner() *OrderModifyResponseLinesInnerAdditionalAttributesInner {
	this := OrderModifyResponseLinesInnerAdditionalAttributesInner{}
	return &this
}

// NewOrderModifyResponseLinesInnerAdditionalAttributesInnerWithDefaults instantiates a new OrderModifyResponseLinesInnerAdditionalAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderModifyResponseLinesInnerAdditionalAttributesInnerWithDefaults() *OrderModifyResponseLinesInnerAdditionalAttributesInner {
	this := OrderModifyResponseLinesInnerAdditionalAttributesInner{}
	return &this
}

// GetAttributeName returns the AttributeName field value if set, zero value otherwise.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) GetAttributeName() string {
	if o == nil || IsNil(o.AttributeName) {
		var ret string
		return ret
	}
	return *o.AttributeName
}

// GetAttributeNameOk returns a tuple with the AttributeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) GetAttributeNameOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeName) {
		return nil, false
	}
	return o.AttributeName, true
}

// HasAttributeName returns a boolean if a field has been set.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) HasAttributeName() bool {
	if o != nil && !IsNil(o.AttributeName) {
		return true
	}

	return false
}

// SetAttributeName gets a reference to the given string and assigns it to the AttributeName field.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) SetAttributeName(v string) {
	o.AttributeName = &v
}

// GetAttributeValue returns the AttributeValue field value if set, zero value otherwise.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) GetAttributeValue() string {
	if o == nil || IsNil(o.AttributeValue) {
		var ret string
		return ret
	}
	return *o.AttributeValue
}

// GetAttributeValueOk returns a tuple with the AttributeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) GetAttributeValueOk() (*string, bool) {
	if o == nil || IsNil(o.AttributeValue) {
		return nil, false
	}
	return o.AttributeValue, true
}

// HasAttributeValue returns a boolean if a field has been set.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) HasAttributeValue() bool {
	if o != nil && !IsNil(o.AttributeValue) {
		return true
	}

	return false
}

// SetAttributeValue gets a reference to the given string and assigns it to the AttributeValue field.
func (o *OrderModifyResponseLinesInnerAdditionalAttributesInner) SetAttributeValue(v string) {
	o.AttributeValue = &v
}

func (o OrderModifyResponseLinesInnerAdditionalAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderModifyResponseLinesInnerAdditionalAttributesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttributeName) {
		toSerialize["attributeName"] = o.AttributeName
	}
	if !IsNil(o.AttributeValue) {
		toSerialize["attributeValue"] = o.AttributeValue
	}
	return toSerialize, nil
}

type NullableOrderModifyResponseLinesInnerAdditionalAttributesInner struct {
	value *OrderModifyResponseLinesInnerAdditionalAttributesInner
	isSet bool
}

func (v NullableOrderModifyResponseLinesInnerAdditionalAttributesInner) Get() *OrderModifyResponseLinesInnerAdditionalAttributesInner {
	return v.value
}

func (v *NullableOrderModifyResponseLinesInnerAdditionalAttributesInner) Set(val *OrderModifyResponseLinesInnerAdditionalAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderModifyResponseLinesInnerAdditionalAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderModifyResponseLinesInnerAdditionalAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderModifyResponseLinesInnerAdditionalAttributesInner(val *OrderModifyResponseLinesInnerAdditionalAttributesInner) *NullableOrderModifyResponseLinesInnerAdditionalAttributesInner {
	return &NullableOrderModifyResponseLinesInnerAdditionalAttributesInner{value: val, isSet: true}
}

func (v NullableOrderModifyResponseLinesInnerAdditionalAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderModifyResponseLinesInnerAdditionalAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


