/*
XI Sdk Resellers

For Resellers seeking to innovate with Ingram Micro's API solutions, automate your eCommerce experience with our array of API's and webhooks to craft a seamless journey for your customers.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xi_sdk_resellers

import (
	"encoding/json"
)

// checks if the QuoteDetailsResponseResellerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuoteDetailsResponseResellerInfo{}

// QuoteDetailsResponseResellerInfo struct for QuoteDetailsResponseResellerInfo
type QuoteDetailsResponseResellerInfo struct {
	// Contact Name
	Contact *string `json:"contact,omitempty"`
	// Ingram Micro Customer's Account Name
	CompanyName *string `json:"companyName,omitempty"`
	// Account Contact Email Address
	Email *string `json:"email,omitempty"`
	// Account Phone Number
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// Reseller account number
	CustomerNumber *string `json:"customerNumber,omitempty"`
}

// NewQuoteDetailsResponseResellerInfo instantiates a new QuoteDetailsResponseResellerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuoteDetailsResponseResellerInfo() *QuoteDetailsResponseResellerInfo {
	this := QuoteDetailsResponseResellerInfo{}
	return &this
}

// NewQuoteDetailsResponseResellerInfoWithDefaults instantiates a new QuoteDetailsResponseResellerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuoteDetailsResponseResellerInfoWithDefaults() *QuoteDetailsResponseResellerInfo {
	this := QuoteDetailsResponseResellerInfo{}
	return &this
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *QuoteDetailsResponseResellerInfo) GetContact() string {
	if o == nil || IsNil(o.Contact) {
		var ret string
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseResellerInfo) GetContactOk() (*string, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *QuoteDetailsResponseResellerInfo) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given string and assigns it to the Contact field.
func (o *QuoteDetailsResponseResellerInfo) SetContact(v string) {
	o.Contact = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *QuoteDetailsResponseResellerInfo) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseResellerInfo) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *QuoteDetailsResponseResellerInfo) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *QuoteDetailsResponseResellerInfo) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *QuoteDetailsResponseResellerInfo) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseResellerInfo) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *QuoteDetailsResponseResellerInfo) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *QuoteDetailsResponseResellerInfo) SetEmail(v string) {
	o.Email = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *QuoteDetailsResponseResellerInfo) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseResellerInfo) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *QuoteDetailsResponseResellerInfo) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *QuoteDetailsResponseResellerInfo) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetCustomerNumber returns the CustomerNumber field value if set, zero value otherwise.
func (o *QuoteDetailsResponseResellerInfo) GetCustomerNumber() string {
	if o == nil || IsNil(o.CustomerNumber) {
		var ret string
		return ret
	}
	return *o.CustomerNumber
}

// GetCustomerNumberOk returns a tuple with the CustomerNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuoteDetailsResponseResellerInfo) GetCustomerNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerNumber) {
		return nil, false
	}
	return o.CustomerNumber, true
}

// HasCustomerNumber returns a boolean if a field has been set.
func (o *QuoteDetailsResponseResellerInfo) HasCustomerNumber() bool {
	if o != nil && !IsNil(o.CustomerNumber) {
		return true
	}

	return false
}

// SetCustomerNumber gets a reference to the given string and assigns it to the CustomerNumber field.
func (o *QuoteDetailsResponseResellerInfo) SetCustomerNumber(v string) {
	o.CustomerNumber = &v
}

func (o QuoteDetailsResponseResellerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuoteDetailsResponseResellerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.CompanyName) {
		toSerialize["companyName"] = o.CompanyName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.CustomerNumber) {
		toSerialize["customerNumber"] = o.CustomerNumber
	}
	return toSerialize, nil
}

type NullableQuoteDetailsResponseResellerInfo struct {
	value *QuoteDetailsResponseResellerInfo
	isSet bool
}

func (v NullableQuoteDetailsResponseResellerInfo) Get() *QuoteDetailsResponseResellerInfo {
	return v.value
}

func (v *NullableQuoteDetailsResponseResellerInfo) Set(val *QuoteDetailsResponseResellerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableQuoteDetailsResponseResellerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableQuoteDetailsResponseResellerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuoteDetailsResponseResellerInfo(val *QuoteDetailsResponseResellerInfo) *NullableQuoteDetailsResponseResellerInfo {
	return &NullableQuoteDetailsResponseResellerInfo{value: val, isSet: true}
}

func (v NullableQuoteDetailsResponseResellerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuoteDetailsResponseResellerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


